// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/workflow-agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_proto_workflow_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_workflow_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartTaskRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_proto_workflow_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_workflow_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StartTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartTaskResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type TaskActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActionRequest) Reset() {
	*x = TaskActionRequest{}
	mi := &file_proto_workflow_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActionRequest) ProtoMessage() {}

func (x *TaskActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActionRequest.ProtoReflect.Descriptor instead.
func (*TaskActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_workflow_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskActionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type TaskActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActionResponse) Reset() {
	*x = TaskActionResponse{}
	mi := &file_proto_workflow_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActionResponse) ProtoMessage() {}

func (x *TaskActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActionResponse.ProtoReflect.Descriptor instead.
func (*TaskActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_workflow_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TaskActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_workflow_agent_proto protoreflect.FileDescriptor

const file_proto_workflow_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/workflow-agent.proto\x12\x05agent\x1a\x1cgoogle/protobuf/struct.proto\"d\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"j\n" +
	"\x11StartTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"6\n" +
	"\x11TaskActionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"H\n" +
	"\x12TaskActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x94\x02\n" +
	"\fAgentService\x12>\n" +
	"\tStartTask\x12\x17.agent.StartTaskRequest\x1a\x18.agent.StartTaskResponse\x12?\n" +
	"\bStopTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponse\x12@\n" +
	"\tPauseTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponse\x12A\n" +
	"\n" +
	"ResumeTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponseB\x10Z\x0einternal/protob\x06proto3"

var (
	file_proto_workflow_agent_proto_rawDescOnce sync.Once
	file_proto_workflow_agent_proto_rawDescData []byte
)

func file_proto_workflow_agent_proto_rawDescGZIP() []byte {
	file_proto_workflow_agent_proto_rawDescOnce.Do(func() {
		file_proto_workflow_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workflow_agent_proto_rawDesc), len(file_proto_workflow_agent_proto_rawDesc)))
	})
	return file_proto_workflow_agent_proto_rawDescData
}

var file_proto_workflow_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_workflow_agent_proto_goTypes = []any{
	(*StartTaskRequest)(nil),   // 0: agent.StartTaskRequest
	(*StartTaskResponse)(nil),  // 1: agent.StartTaskResponse
	(*TaskActionRequest)(nil),  // 2: agent.TaskActionRequest
	(*TaskActionResponse)(nil), // 3: agent.TaskActionResponse
	(*structpb.Struct)(nil),    // 4: google.protobuf.Struct
}
var file_proto_workflow_agent_proto_depIdxs = []int32{
	4, // 0: agent.StartTaskRequest.parameters:type_name -> google.protobuf.Struct
	0, // 1: agent.AgentService.StartTask:input_type -> agent.StartTaskRequest
	2, // 2: agent.AgentService.StopTask:input_type -> agent.TaskActionRequest
	2, // 3: agent.AgentService.PauseTask:input_type -> agent.TaskActionRequest
	2, // 4: agent.AgentService.ResumeTask:input_type -> agent.TaskActionRequest
	1, // 5: agent.AgentService.StartTask:output_type -> agent.StartTaskResponse
	3, // 6: agent.AgentService.StopTask:output_type -> agent.TaskActionResponse
	3, // 7: agent.AgentService.PauseTask:output_type -> agent.TaskActionResponse
	3, // 8: agent.AgentService.ResumeTask:output_type -> agent.TaskActionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_workflow_agent_proto_init() }
func file_proto_workflow_agent_proto_init() {
	if File_proto_workflow_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workflow_agent_proto_rawDesc), len(file_proto_workflow_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workflow_agent_proto_goTypes,
		DependencyIndexes: file_proto_workflow_agent_proto_depIdxs,
		MessageInfos:      file_proto_workflow_agent_proto_msgTypes,
	}.Build()
	File_proto_workflow_agent_proto = out.File
	file_proto_workflow_agent_proto_goTypes = nil
	file_proto_workflow_agent_proto_depIdxs = nil
}
