// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/workflow-engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowEngine_StartWorkflow_FullMethodName = "/engine.WorkflowEngine/StartWorkflow"
)

// WorkflowEngineClient is the client API for WorkflowEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowEngineClient interface {
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
}

type workflowEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowEngineClient(cc grpc.ClientConnInterface) WorkflowEngineClient {
	return &workflowEngineClient{cc}
}

func (c *workflowEngineClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowEngine_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowEngineServer is the server API for WorkflowEngine service.
// All implementations must embed UnimplementedWorkflowEngineServer
// for forward compatibility.
type WorkflowEngineServer interface {
	StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error)
	mustEmbedUnimplementedWorkflowEngineServer()
}

// UnimplementedWorkflowEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowEngineServer struct{}

func (UnimplementedWorkflowEngineServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedWorkflowEngineServer) mustEmbedUnimplementedWorkflowEngineServer() {}
func (UnimplementedWorkflowEngineServer) testEmbeddedByValue()                        {}

// UnsafeWorkflowEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowEngineServer will
// result in compilation errors.
type UnsafeWorkflowEngineServer interface {
	mustEmbedUnimplementedWorkflowEngineServer()
}

func RegisterWorkflowEngineServer(s grpc.ServiceRegistrar, srv WorkflowEngineServer) {
	// If the following call pancis, it indicates UnimplementedWorkflowEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowEngine_ServiceDesc, srv)
}

func _WorkflowEngine_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowEngineServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowEngine_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowEngineServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowEngine_ServiceDesc is the grpc.ServiceDesc for WorkflowEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.WorkflowEngine",
	HandlerType: (*WorkflowEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorkflow",
			Handler:    _WorkflowEngine_StartWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workflow-engine.proto",
}
