version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: wf-engine-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wf-engine-main
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "50051:50051"
    command: ["./engine"]
    env_file:
      - .env

volumes:
  pg_data: