version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: wf-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: