/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentOverviewResponse,
  AgentResponse,
} from '../models/index';
import {
    AgentOverviewResponseFromJSON,
    AgentOverviewResponseToJSON,
    AgentResponseFromJSON,
    AgentResponseToJSON,
} from '../models/index';

export interface GetAgentByNameRequest {
    name: string;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Retrieve detailed information about a specific agent by its name.
     * Get agent by name
     */
    async getAgentByNameRaw(requestParameters: GetAgentByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getAgentByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/agents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific agent by its name.
     * Get agent by name
     */
    async getAgentByName(requestParameters: GetAgentByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.getAgentByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of all registered agents in the system.
     * Get all registered agents
     */
    async getAllAgentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AgentOverviewResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/agents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentOverviewResponseFromJSON));
    }

    /**
     * Retrieve a list of all registered agents in the system.
     * Get all registered agents
     */
    async getAllAgents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AgentOverviewResponse>> {
        const response = await this.getAllAgentsRaw(initOverrides);
        return await response.value();
    }

}
