/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StepInstance,
} from '../models/index';
import {
    StepInstanceFromJSON,
    StepInstanceToJSON,
} from '../models/index';

export interface GetAllStepInstancesRequest {
    limit?: number;
    offset?: number;
}

export interface GetStepInstanceByIdRequest {
    id: string;
}

/**
 * 
 */
export class StepInstancesApi extends runtime.BaseAPI {

    /**
     * Get all step instances with pagination
     * Get all step instances
     */
    async getAllStepInstancesRaw(requestParameters: GetAllStepInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StepInstance>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/step-instances`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StepInstanceFromJSON));
    }

    /**
     * Get all step instances with pagination
     * Get all step instances
     */
    async getAllStepInstances(requestParameters: GetAllStepInstancesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StepInstance>> {
        const response = await this.getAllStepInstancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a step instance by its ID
     * Get step instance by ID
     */
    async getStepInstanceByIdRaw(requestParameters: GetStepInstanceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StepInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStepInstanceById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/step-instances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StepInstanceFromJSON(jsonValue));
    }

    /**
     * Get a step instance by its ID
     * Get step instance by ID
     */
    async getStepInstanceById(requestParameters: GetStepInstanceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StepInstance> {
        const response = await this.getStepInstanceByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
