/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TaskDefinitionResponse,
} from '../models/index';
import {
    TaskDefinitionResponseFromJSON,
    TaskDefinitionResponseToJSON,
} from '../models/index';

export interface GetTaskDefinitionByIdRequest {
    id: string;
}

/**
 * 
 */
export class TaskDefinitionsApi extends runtime.BaseAPI {

    /**
     * Get all task definitions
     * Get all task definitions
     */
    async getAllTaskDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskDefinitionResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/task-definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskDefinitionResponseFromJSON));
    }

    /**
     * Get all task definitions
     * Get all task definitions
     */
    async getAllTaskDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskDefinitionResponse>> {
        const response = await this.getAllTaskDefinitionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get task definition by ID
     * Get task definition by ID
     */
    async getTaskDefinitionByIdRaw(requestParameters: GetTaskDefinitionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDefinitionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTaskDefinitionById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/task-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDefinitionResponseFromJSON(jsonValue));
    }

    /**
     * Get task definition by ID
     * Get task definition by ID
     */
    async getTaskDefinitionById(requestParameters: GetTaskDefinitionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDefinitionResponse> {
        const response = await this.getTaskDefinitionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
