/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WorkflowInstance,
} from '../models/index';
import {
    WorkflowInstanceFromJSON,
    WorkflowInstanceToJSON,
} from '../models/index';

export interface GetWorkflowInstanceByIDRequest {
    id: string;
}

/**
 * 
 */
export class WorkflowInstancesApi extends runtime.BaseAPI {

    /**
     * Get all workflow instances
     * Get all workflow instances
     */
    async getAllWorkflowInstancesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkflowInstance>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workflow-instances`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkflowInstanceFromJSON));
    }

    /**
     * Get all workflow instances
     * Get all workflow instances
     */
    async getAllWorkflowInstances(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkflowInstance>> {
        const response = await this.getAllWorkflowInstancesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a workflow instance by ID
     * Get a workflow instance by ID
     */
    async getWorkflowInstanceByIDRaw(requestParameters: GetWorkflowInstanceByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowInstanceByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workflow-instances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowInstanceFromJSON(jsonValue));
    }

    /**
     * Get a workflow instance by ID
     * Get a workflow instance by ID
     */
    async getWorkflowInstanceByID(requestParameters: GetWorkflowInstanceByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowInstance> {
        const response = await this.getWorkflowInstanceByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
