/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UpdateWorkflowDefRequest,
  WorkflowDefinition,
} from '../models/index';
import {
    UpdateWorkflowDefRequestFromJSON,
    UpdateWorkflowDefRequestToJSON,
    WorkflowDefinitionFromJSON,
    WorkflowDefinitionToJSON,
} from '../models/index';

export interface CreateWorkflowDefinitionRequest {
    definition: WorkflowDefinition;
}

export interface DeleteWorkflowDefinitionRequest {
    id: string;
}

export interface DisableWorkflowDefinitionRequest {
    id: string;
}

export interface EnableWorkflowDefinitionRequest {
    id: string;
}

export interface GetWorkflowDefinitionByIDRequest {
    id: string;
}

export interface PublishWorkflowDefinitionRequest {
    id: string;
}

export interface UpdateWorkflowDefinitionRequest {
    id: string;
    definition: UpdateWorkflowDefRequest;
}

/**
 * 
 */
export class WorkflowDefinitionsApi extends runtime.BaseAPI {

    /**
     * Create a new workflow definition
     * Create a new workflow definition
     */
    async createWorkflowDefinitionRaw(requestParameters: CreateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['definition'] == null) {
            throw new runtime.RequiredError(
                'definition',
                'Required parameter "definition" was null or undefined when calling createWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workflow-definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowDefinitionToJSON(requestParameters['definition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Create a new workflow definition
     * Create a new workflow definition
     */
    async createWorkflowDefinition(requestParameters: CreateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.createWorkflowDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async deleteWorkflowDefinitionRaw(requestParameters: DeleteWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async deleteWorkflowDefinition(requestParameters: DeleteWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async disableWorkflowDefinitionRaw(requestParameters: DisableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling disableWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/disable`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async disableWorkflowDefinition(requestParameters: DisableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.disableWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async enableWorkflowDefinitionRaw(requestParameters: EnableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enableWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/enable`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a workflow definition
     * Delete a workflow definition
     */
    async enableWorkflowDefinition(requestParameters: EnableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enableWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Get all workflow definitions
     * Get all workflow definitions
     */
    async getAllWorkflowDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkflowDefinition>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkflowDefinitionFromJSON));
    }

    /**
     * Get all workflow definitions
     * Get all workflow definitions
     */
    async getAllWorkflowDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkflowDefinition>> {
        const response = await this.getAllWorkflowDefinitionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a workflow definition by ID
     * Get a workflow definition by ID
     */
    async getWorkflowDefinitionByIDRaw(requestParameters: GetWorkflowDefinitionByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowDefinitionByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Get a workflow definition by ID
     * Get a workflow definition by ID
     */
    async getWorkflowDefinitionByID(requestParameters: GetWorkflowDefinitionByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.getWorkflowDefinitionByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish a workflow definition
     * Publish a workflow definition
     */
    async publishWorkflowDefinitionRaw(requestParameters: PublishWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publishWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/publish`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Publish a workflow definition
     * Publish a workflow definition
     */
    async publishWorkflowDefinition(requestParameters: PublishWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Update an existing workflow definition
     * Update an existing workflow definition
     */
    async updateWorkflowDefinitionRaw(requestParameters: UpdateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWorkflowDefinition().'
            );
        }

        if (requestParameters['definition'] == null) {
            throw new runtime.RequiredError(
                'definition',
                'Required parameter "definition" was null or undefined when calling updateWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWorkflowDefRequestToJSON(requestParameters['definition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Update an existing workflow definition
     * Update an existing workflow definition
     */
    async updateWorkflowDefinition(requestParameters: UpdateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.updateWorkflowDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
