/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Expression,
  WorkflowDefinition,
} from '../models/index';
import {
    ExpressionFromJSON,
    ExpressionToJSON,
    WorkflowDefinitionFromJSON,
    WorkflowDefinitionToJSON,
} from '../models/index';

export interface CreateWorkflowDefinitionRequest {
    body: WorkflowDefinition;
    draft?: boolean;
}

export interface DeleteWorkflowDefinitionRequest {
    id: string;
}

export interface DisableWorkflowDefinitionRequest {
    id: string;
}

export interface EnableWorkflowDefinitionRequest {
    id: string;
}

export interface GetAllWorkflowDefinitionsRequest {
    page?: number;
    pageSize?: number;
}

export interface GetWorkflowDefinitionByIDRequest {
    id: string;
}

export interface PublishWorkflowDefinitionRequest {
    id: string;
}

export interface SearchWorkflowDefinitionsRequest {
    expression: Expression;
    page?: number;
    pageSize?: number;
}

export interface UpdateWorkflowDefinitionRequest {
    id: string;
    body: WorkflowDefinition;
}

/**
 * 
 */
export class WorkflowDefinitionsApi extends runtime.BaseAPI {

    /**
     * Create a new workflow definition, optionally as a draft
     * Create a new workflow definition
     */
    async createWorkflowDefinitionRaw(requestParameters: CreateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['draft'] != null) {
            queryParameters['draft'] = requestParameters['draft'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workflow-definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowDefinitionToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Create a new workflow definition, optionally as a draft
     * Create a new workflow definition
     */
    async createWorkflowDefinition(requestParameters: CreateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.createWorkflowDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a workflow definition by its ID
     * Delete a workflow definition
     */
    async deleteWorkflowDefinitionRaw(requestParameters: DeleteWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a workflow definition by its ID
     * Delete a workflow definition
     */
    async deleteWorkflowDefinition(requestParameters: DeleteWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Disable a workflow definition by its ID
     * Disable a workflow definition
     */
    async disableWorkflowDefinitionRaw(requestParameters: DisableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling disableWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/disable`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Disable a workflow definition by its ID
     * Disable a workflow definition
     */
    async disableWorkflowDefinition(requestParameters: DisableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.disableWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Enable a workflow definition by its ID
     * Enable a workflow definition
     */
    async enableWorkflowDefinitionRaw(requestParameters: EnableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enableWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/enable`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Enable a workflow definition by its ID
     * Enable a workflow definition
     */
    async enableWorkflowDefinition(requestParameters: EnableWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enableWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a paginated list of all workflow definitions
     * Get all workflow definitions
     */
    async getAllWorkflowDefinitionsRaw(requestParameters: GetAllWorkflowDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkflowDefinition>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkflowDefinitionFromJSON));
    }

    /**
     * Retrieve a paginated list of all workflow definitions
     * Get all workflow definitions
     */
    async getAllWorkflowDefinitions(requestParameters: GetAllWorkflowDefinitionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkflowDefinition>> {
        const response = await this.getAllWorkflowDefinitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a workflow definition by its ID
     * Get workflow definition by ID
     */
    async getWorkflowDefinitionByIDRaw(requestParameters: GetWorkflowDefinitionByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowDefinitionByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Retrieve a workflow definition by its ID
     * Get workflow definition by ID
     */
    async getWorkflowDefinitionByID(requestParameters: GetWorkflowDefinitionByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.getWorkflowDefinitionByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish a draft workflow definition by its ID
     * Publish a workflow definition
     */
    async publishWorkflowDefinitionRaw(requestParameters: PublishWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publishWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/workflow-definitions/{id}/publish`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Publish a draft workflow definition by its ID
     * Publish a workflow definition
     */
    async publishWorkflowDefinition(requestParameters: PublishWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishWorkflowDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Search for workflow definitions based on a given expression
     * Search workflow definitions
     */
    async searchWorkflowDefinitionsRaw(requestParameters: SearchWorkflowDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkflowDefinition>>> {
        if (requestParameters['expression'] == null) {
            throw new runtime.RequiredError(
                'expression',
                'Required parameter "expression" was null or undefined when calling searchWorkflowDefinitions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workflow-definitions/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExpressionToJSON(requestParameters['expression']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkflowDefinitionFromJSON));
    }

    /**
     * Search for workflow definitions based on a given expression
     * Search workflow definitions
     */
    async searchWorkflowDefinitions(requestParameters: SearchWorkflowDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkflowDefinition>> {
        const response = await this.searchWorkflowDefinitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing workflow definition by its ID
     * Update an existing workflow definition
     */
    async updateWorkflowDefinitionRaw(requestParameters: UpdateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDefinition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWorkflowDefinition().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateWorkflowDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workflow-definitions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowDefinitionToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDefinitionFromJSON(jsonValue));
    }

    /**
     * Update an existing workflow definition by its ID
     * Update an existing workflow definition
     */
    async updateWorkflowDefinition(requestParameters: UpdateWorkflowDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDefinition> {
        const response = await this.updateWorkflowDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
