// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_UNKNOWN   TaskStatus = 0
	TaskStatus_PENDING   TaskStatus = 1
	TaskStatus_RUNNING   TaskStatus = 2
	TaskStatus_COMPLETED TaskStatus = 3
	TaskStatus_FAILED    TaskStatus = 4
	TaskStatus_PAUSED    TaskStatus = 5
	TaskStatus_STOPPED   TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "PAUSED",
		6: "STOPPED",
	}
	TaskStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"FAILED":    4,
		"PAUSED":    5,
		"STOPPED":   6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type TaskDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InputParameters  *structpb.Struct       `protobuf:"bytes,4,opt,name=input_parameters,json=inputParameters,proto3" json:"input_parameters,omitempty"`
	OutputParameters *structpb.Struct       `protobuf:"bytes,5,opt,name=output_parameters,json=outputParameters,proto3" json:"output_parameters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskDefinition) GetInputParameters() *structpb.Struct {
	if x != nil {
		return x.InputParameters
	}
	return nil
}

func (x *TaskDefinition) GetOutputParameters() *structpb.Struct {
	if x != nil {
		return x.OutputParameters
	}
	return nil
}

type PingAgentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedTasks []*TaskDefinition      `protobuf:"bytes,3,rep,name=supported_tasks,json=supportedTasks,proto3" json:"supported_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingAgentResponse) Reset() {
	*x = PingAgentResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingAgentResponse) ProtoMessage() {}

func (x *PingAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingAgentResponse.ProtoReflect.Descriptor instead.
func (*PingAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingAgentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PingAgentResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingAgentResponse) GetSupportedTasks() []*TaskDefinition {
	if x != nil {
		return x.SupportedTasks
	}
	return nil
}

type StartTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskName        string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	InputParameters *structpb.Struct       `protobuf:"bytes,2,opt,name=input_parameters,json=inputParameters,proto3" json:"input_parameters,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StartTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *StartTaskRequest) GetInputParameters() *structpb.Struct {
	if x != nil {
		return x.InputParameters
	}
	return nil
}

func (x *StartTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TaskActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActionRequest) Reset() {
	*x = TaskActionRequest{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActionRequest) ProtoMessage() {}

func (x *TaskActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActionRequest.ProtoReflect.Descriptor instead.
func (*TaskActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TaskActionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActionResponse) Reset() {
	*x = TaskActionResponse{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActionResponse) ProtoMessage() {}

func (x *TaskActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActionResponse.ProtoReflect.Descriptor instead.
func (*TaskActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TaskActionResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=agent.TaskStatus" json:"status,omitempty"`
	Progress      float32                `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_UNKNOWN
}

func (x *GetTaskStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetTaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTaskStatusResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe0\x01\n" +
	"\x0eTaskDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x10input_parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0finputParameters\x12D\n" +
	"\x11output_parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x10outputParameters\"\x81\x01\n" +
	"\x11PingAgentResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12>\n" +
	"\x0fsupported_tasks\x18\x03 \x03(\v2\x15.agent.TaskDefinitionR\x0esupportedTasks\"\x9c\x01\n" +
	"\x10StartTaskRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12B\n" +
	"\x10input_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0finputParameters\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\",\n" +
	"\x11TaskActionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"a\n" +
	"\x12TaskActionResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc2\x01\n" +
	"\x15GetTaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.agent.TaskStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x02R\bprogress\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12/\n" +
	"\x06output\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06output*g\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x05\x12\v\n" +
	"\aSTOPPED\x10\x062\x98\x03\n" +
	"\fAgentService\x12?\n" +
	"\tStartTask\x12\x17.agent.StartTaskRequest\x1a\x19.agent.TaskActionResponse\x12G\n" +
	"\rGetTaskStatus\x12\x18.agent.TaskActionRequest\x1a\x1c.agent.GetTaskStatusResponse\x12?\n" +
	"\bStopTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponse\x12@\n" +
	"\tPauseTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponse\x12A\n" +
	"\n" +
	"ResumeTask\x12\x18.agent.TaskActionRequest\x1a\x19.agent.TaskActionResponse\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x18.agent.PingAgentResponseB\x10Z\x0einternal/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_agent_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: agent.TaskStatus
	(*TaskDefinition)(nil),        // 1: agent.TaskDefinition
	(*PingAgentResponse)(nil),     // 2: agent.PingAgentResponse
	(*StartTaskRequest)(nil),      // 3: agent.StartTaskRequest
	(*TaskActionRequest)(nil),     // 4: agent.TaskActionRequest
	(*TaskActionResponse)(nil),    // 5: agent.TaskActionResponse
	(*GetTaskStatusResponse)(nil), // 6: agent.GetTaskStatusResponse
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_proto_agent_proto_depIdxs = []int32{
	7,  // 0: agent.TaskDefinition.input_parameters:type_name -> google.protobuf.Struct
	7,  // 1: agent.TaskDefinition.output_parameters:type_name -> google.protobuf.Struct
	1,  // 2: agent.PingAgentResponse.supported_tasks:type_name -> agent.TaskDefinition
	7,  // 3: agent.StartTaskRequest.input_parameters:type_name -> google.protobuf.Struct
	0,  // 4: agent.GetTaskStatusResponse.status:type_name -> agent.TaskStatus
	7,  // 5: agent.GetTaskStatusResponse.output:type_name -> google.protobuf.Struct
	3,  // 6: agent.AgentService.StartTask:input_type -> agent.StartTaskRequest
	4,  // 7: agent.AgentService.GetTaskStatus:input_type -> agent.TaskActionRequest
	4,  // 8: agent.AgentService.StopTask:input_type -> agent.TaskActionRequest
	4,  // 9: agent.AgentService.PauseTask:input_type -> agent.TaskActionRequest
	4,  // 10: agent.AgentService.ResumeTask:input_type -> agent.TaskActionRequest
	8,  // 11: agent.AgentService.Ping:input_type -> google.protobuf.Empty
	5,  // 12: agent.AgentService.StartTask:output_type -> agent.TaskActionResponse
	6,  // 13: agent.AgentService.GetTaskStatus:output_type -> agent.GetTaskStatusResponse
	5,  // 14: agent.AgentService.StopTask:output_type -> agent.TaskActionResponse
	5,  // 15: agent.AgentService.PauseTask:output_type -> agent.TaskActionResponse
	5,  // 16: agent.AgentService.ResumeTask:output_type -> agent.TaskActionResponse
	2,  // 17: agent.AgentService.Ping:output_type -> agent.PingAgentResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
