// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: definition/agent.proto

package proto

const (
	UNKNOWN   = TaskStatus_UNKNOWN
	PENDING   = TaskStatus_PENDING
	RUNNING   = TaskStatus_RUNNING
	COMPLETED = TaskStatus_COMPLETED
	FAILED    = TaskStatus_FAILED
	PAUSED    = TaskStatus_PAUSED
	STOPPED   = TaskStatus_STOPPED
)
