// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: definition/engine.proto

package proto

const (
	AGENT_PROTOCOL_UNKNOWN = AgentProtocol_AGENT_PROTOCOL_UNKNOWN
	AGENT_PROTOCOL_GRPC    = AgentProtocol_AGENT_PROTOCOL_GRPC
	AGENT_PROTOCOL_HTTP    = AgentProtocol_AGENT_PROTOCOL_HTTP
)
