// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: definition/engine.proto

package proto

const (
	UNKNOWN = AgentProtocol_UNKNOWN
	GRPC    = AgentProtocol_GRPC
	HTTP    = AgentProtocol_HTTP
)
