// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: definition/engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentProtocol int32

const (
	AgentProtocol_AGENT_PROTOCOL_UNKNOWN AgentProtocol = 0
	AgentProtocol_AGENT_PROTOCOL_GRPC    AgentProtocol = 1
	AgentProtocol_AGENT_PROTOCOL_HTTP    AgentProtocol = 2
)

// Enum value maps for AgentProtocol.
var (
	AgentProtocol_name = map[int32]string{
		0: "AGENT_PROTOCOL_UNKNOWN",
		1: "AGENT_PROTOCOL_GRPC",
		2: "AGENT_PROTOCOL_HTTP",
	}
	AgentProtocol_value = map[string]int32{
		"AGENT_PROTOCOL_UNKNOWN": 0,
		"AGENT_PROTOCOL_GRPC":    1,
		"AGENT_PROTOCOL_HTTP":    2,
	}
)

func (x AgentProtocol) Enum() *AgentProtocol {
	p := new(AgentProtocol)
	*p = x
	return p
}

func (x AgentProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_engine_proto_enumTypes[0].Descriptor()
}

func (AgentProtocol) Type() protoreflect.EnumType {
	return &file_definition_engine_proto_enumTypes[0]
}

func (x AgentProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentProtocol.Descriptor instead.
func (AgentProtocol) EnumDescriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{0}
}

type EnginePingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnginePingRequest) Reset() {
	*x = EnginePingRequest{}
	mi := &file_definition_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnginePingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnginePingRequest) ProtoMessage() {}

func (x *EnginePingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnginePingRequest.ProtoReflect.Descriptor instead.
func (*EnginePingRequest) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{0}
}

func (x *EnginePingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnginePingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowAgent     bool                   `protobuf:"varint,1,opt,name=know_agent,json=knowAgent,proto3" json:"know_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnginePingResponse) Reset() {
	*x = EnginePingResponse{}
	mi := &file_definition_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnginePingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnginePingResponse) ProtoMessage() {}

func (x *EnginePingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnginePingResponse.ProtoReflect.Descriptor instead.
func (*EnginePingResponse) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{1}
}

func (x *EnginePingResponse) GetKnowAgent() bool {
	if x != nil {
		return x.KnowAgent
	}
	return false
}

type RegisterAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Address        *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Port           string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Protocol       AgentProtocol          `protobuf:"varint,5,opt,name=protocol,proto3,enum=engine.AgentProtocol" json:"protocol,omitempty"`
	SupportedTasks []*TaskDefinition      `protobuf:"bytes,6,rep,name=supported_tasks,json=supportedTasks,proto3" json:"supported_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_definition_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *RegisterAgentRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegisterAgentRequest) GetProtocol() AgentProtocol {
	if x != nil {
		return x.Protocol
	}
	return AgentProtocol_AGENT_PROTOCOL_UNKNOWN
}

func (x *RegisterAgentRequest) GetSupportedTasks() []*TaskDefinition {
	if x != nil {
		return x.SupportedTasks
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_definition_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type NotifyTaskStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status           TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=agent.TaskStatus" json:"status,omitempty"`
	OutputParameters *structpb.Struct       `protobuf:"bytes,3,opt,name=output_parameters,json=outputParameters,proto3" json:"output_parameters,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotifyTaskStatusRequest) Reset() {
	*x = NotifyTaskStatusRequest{}
	mi := &file_definition_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTaskStatusRequest) ProtoMessage() {}

func (x *NotifyTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*NotifyTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NotifyTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_UNKNOWN
}

func (x *NotifyTaskStatusRequest) GetOutputParameters() *structpb.Struct {
	if x != nil {
		return x.OutputParameters
	}
	return nil
}

func (x *NotifyTaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotifyTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      float32                `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTaskProgressRequest) Reset() {
	*x = NotifyTaskProgressRequest{}
	mi := &file_definition_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTaskProgressRequest) ProtoMessage() {}

func (x *NotifyTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*NotifyTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyTaskProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NotifyTaskProgressRequest) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type StartWorkflowRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowDefinitionId string                 `protobuf:"bytes,1,opt,name=workflow_definition_id,json=workflowDefinitionId,proto3" json:"workflow_definition_id,omitempty"`
	InputParameters      *structpb.Struct       `protobuf:"bytes,2,opt,name=input_parameters,json=inputParameters,proto3" json:"input_parameters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_definition_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{6}
}

func (x *StartWorkflowRequest) GetWorkflowDefinitionId() string {
	if x != nil {
		return x.WorkflowDefinitionId
	}
	return ""
}

func (x *StartWorkflowRequest) GetInputParameters() *structpb.Struct {
	if x != nil {
		return x.InputParameters
	}
	return nil
}

type StartWorkflowResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WorkflowInstanceId *string                `protobuf:"bytes,2,opt,name=workflow_instance_id,json=workflowInstanceId,proto3,oneof" json:"workflow_instance_id,omitempty"`
	Message            *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_definition_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_definition_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_definition_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StartWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartWorkflowResponse) GetWorkflowInstanceId() string {
	if x != nil && x.WorkflowInstanceId != nil {
		return *x.WorkflowInstanceId
	}
	return ""
}

func (x *StartWorkflowResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_definition_engine_proto protoreflect.FileDescriptor

const file_definition_engine_proto_rawDesc = "" +
	"\n" +
	"\x17definition/engine.proto\x12\x06engine\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x16definition/agent.proto\"'\n" +
	"\x11EnginePingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x12EnginePingResponse\x12\x1d\n" +
	"\n" +
	"know_agent\x18\x01 \x01(\bR\tknowAgent\"\xf6\x01\n" +
	"\x14RegisterAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x121\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x15.engine.AgentProtocolR\bprotocol\x12>\n" +
	"\x0fsupported_tasks\x18\x06 \x03(\v2\x15.agent.TaskDefinitionR\x0esupportedTasksB\n" +
	"\n" +
	"\b_address\"\\\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xbd\x01\n" +
	"\x17NotifyTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.agent.TaskStatusR\x06status\x12D\n" +
	"\x11output_parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x10outputParameters\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"P\n" +
	"\x19NotifyTaskProgressRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x02R\bprogress\"\x90\x01\n" +
	"\x14StartWorkflowRequest\x124\n" +
	"\x16workflow_definition_id\x18\x01 \x01(\tR\x14workflowDefinitionId\x12B\n" +
	"\x10input_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0finputParameters\"\xac\x01\n" +
	"\x15StartWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\x14workflow_instance_id\x18\x02 \x01(\tH\x00R\x12workflowInstanceId\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\x17\n" +
	"\x15_workflow_instance_idB\n" +
	"\n" +
	"\b_message*]\n" +
	"\rAgentProtocol\x12\x1a\n" +
	"\x16AGENT_PROTOCOL_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13AGENT_PROTOCOL_GRPC\x10\x01\x12\x17\n" +
	"\x13AGENT_PROTOCOL_HTTP\x10\x022\xab\x01\n" +
	"\vTaskService\x12K\n" +
	"\x10NotifyTaskStatus\x12\x1f.engine.NotifyTaskStatusRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x12NotifyTaskProgress\x12!.engine.NotifyTaskProgressRequest\x1a\x16.google.protobuf.Empty2\xea\x01\n" +
	"\rEngineService\x12L\n" +
	"\rRegisterAgent\x12\x1c.engine.RegisterAgentRequest\x1a\x1d.engine.RegisterAgentResponse\x12=\n" +
	"\x04Ping\x12\x19.engine.EnginePingRequest\x1a\x1a.engine.EnginePingResponse\x12L\n" +
	"\rStartWorkflow\x12\x1c.engine.StartWorkflowRequest\x1a\x1d.engine.StartWorkflowResponseB\tZ\a./protob\x06proto3"

var (
	file_definition_engine_proto_rawDescOnce sync.Once
	file_definition_engine_proto_rawDescData []byte
)

func file_definition_engine_proto_rawDescGZIP() []byte {
	file_definition_engine_proto_rawDescOnce.Do(func() {
		file_definition_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definition_engine_proto_rawDesc), len(file_definition_engine_proto_rawDesc)))
	})
	return file_definition_engine_proto_rawDescData
}

var file_definition_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_definition_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_definition_engine_proto_goTypes = []any{
	(AgentProtocol)(0),                // 0: engine.AgentProtocol
	(*EnginePingRequest)(nil),         // 1: engine.EnginePingRequest
	(*EnginePingResponse)(nil),        // 2: engine.EnginePingResponse
	(*RegisterAgentRequest)(nil),      // 3: engine.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),     // 4: engine.RegisterAgentResponse
	(*NotifyTaskStatusRequest)(nil),   // 5: engine.NotifyTaskStatusRequest
	(*NotifyTaskProgressRequest)(nil), // 6: engine.NotifyTaskProgressRequest
	(*StartWorkflowRequest)(nil),      // 7: engine.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),     // 8: engine.StartWorkflowResponse
	(*TaskDefinition)(nil),            // 9: agent.TaskDefinition
	(TaskStatus)(0),                   // 10: agent.TaskStatus
	(*structpb.Struct)(nil),           // 11: google.protobuf.Struct
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
}
var file_definition_engine_proto_depIdxs = []int32{
	0,  // 0: engine.RegisterAgentRequest.protocol:type_name -> engine.AgentProtocol
	9,  // 1: engine.RegisterAgentRequest.supported_tasks:type_name -> agent.TaskDefinition
	10, // 2: engine.NotifyTaskStatusRequest.status:type_name -> agent.TaskStatus
	11, // 3: engine.NotifyTaskStatusRequest.output_parameters:type_name -> google.protobuf.Struct
	11, // 4: engine.StartWorkflowRequest.input_parameters:type_name -> google.protobuf.Struct
	5,  // 5: engine.TaskService.NotifyTaskStatus:input_type -> engine.NotifyTaskStatusRequest
	6,  // 6: engine.TaskService.NotifyTaskProgress:input_type -> engine.NotifyTaskProgressRequest
	3,  // 7: engine.EngineService.RegisterAgent:input_type -> engine.RegisterAgentRequest
	1,  // 8: engine.EngineService.Ping:input_type -> engine.EnginePingRequest
	7,  // 9: engine.EngineService.StartWorkflow:input_type -> engine.StartWorkflowRequest
	12, // 10: engine.TaskService.NotifyTaskStatus:output_type -> google.protobuf.Empty
	12, // 11: engine.TaskService.NotifyTaskProgress:output_type -> google.protobuf.Empty
	4,  // 12: engine.EngineService.RegisterAgent:output_type -> engine.RegisterAgentResponse
	2,  // 13: engine.EngineService.Ping:output_type -> engine.EnginePingResponse
	8,  // 14: engine.EngineService.StartWorkflow:output_type -> engine.StartWorkflowResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_definition_engine_proto_init() }
func file_definition_engine_proto_init() {
	if File_definition_engine_proto != nil {
		return
	}
	file_definition_agent_proto_init()
	file_definition_engine_proto_msgTypes[2].OneofWrappers = []any{}
	file_definition_engine_proto_msgTypes[3].OneofWrappers = []any{}
	file_definition_engine_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definition_engine_proto_rawDesc), len(file_definition_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_definition_engine_proto_goTypes,
		DependencyIndexes: file_definition_engine_proto_depIdxs,
		EnumInfos:         file_definition_engine_proto_enumTypes,
		MessageInfos:      file_definition_engine_proto_msgTypes,
	}.Build()
	File_definition_engine_proto = out.File
	file_definition_engine_proto_goTypes = nil
	file_definition_engine_proto_depIdxs = nil
}
