// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: definition/websocket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsocketScopeType int32

const (
	WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED       WebsocketScopeType = 0
	WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE WebsocketScopeType = 1
)

// Enum value maps for WebsocketScopeType.
var (
	WebsocketScopeType_name = map[int32]string{
		0: "WEBSOCKET_SCOPE_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE",
	}
	WebsocketScopeType_value = map[string]int32{
		"WEBSOCKET_SCOPE_TYPE_UNSPECIFIED":       0,
		"WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE": 1,
	}
)

func (x WebsocketScopeType) Enum() *WebsocketScopeType {
	p := new(WebsocketScopeType)
	*p = x
	return p
}

func (x WebsocketScopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketScopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[0].Descriptor()
}

func (WebsocketScopeType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[0]
}

func (x WebsocketScopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketScopeType.Descriptor instead.
func (WebsocketScopeType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{0}
}

type WebsocketMessageType int32

const (
	WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED             WebsocketMessageType = 0
	WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT WebsocketMessageType = 1
)

// Enum value maps for WebsocketMessageType.
var (
	WebsocketMessageType_name = map[int32]string{
		0: "WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT",
	}
	WebsocketMessageType_value = map[string]int32{
		"WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED":             0,
		"WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT": 1,
	}
)

func (x WebsocketMessageType) Enum() *WebsocketMessageType {
	p := new(WebsocketMessageType)
	*p = x
	return p
}

func (x WebsocketMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[1].Descriptor()
}

func (WebsocketMessageType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[1]
}

func (x WebsocketMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketMessageType.Descriptor instead.
func (WebsocketMessageType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{1}
}

type WebsocketCommandType int32

const (
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSPECIFIED WebsocketCommandType = 0
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_SUBSCRIBE   WebsocketCommandType = 1
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE WebsocketCommandType = 2
)

// Enum value maps for WebsocketCommandType.
var (
	WebsocketCommandType_name = map[int32]string{
		0: "WEBSOCKET_COMMAND_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_COMMAND_TYPE_SUBSCRIBE",
		2: "WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE",
	}
	WebsocketCommandType_value = map[string]int32{
		"WEBSOCKET_COMMAND_TYPE_UNSPECIFIED": 0,
		"WEBSOCKET_COMMAND_TYPE_SUBSCRIBE":   1,
		"WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE": 2,
	}
)

func (x WebsocketCommandType) Enum() *WebsocketCommandType {
	p := new(WebsocketCommandType)
	*p = x
	return p
}

func (x WebsocketCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[2].Descriptor()
}

func (WebsocketCommandType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[2]
}

func (x WebsocketCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketCommandType.Descriptor instead.
func (WebsocketCommandType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{2}
}

type WorkflowInstanceEventType int32

const (
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED WorkflowInstanceEventType = 0
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_STARTED     WorkflowInstanceEventType = 1
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED     WorkflowInstanceEventType = 2
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED   WorkflowInstanceEventType = 3
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_FAILED      WorkflowInstanceEventType = 4
)

// Enum value maps for WorkflowInstanceEventType.
var (
	WorkflowInstanceEventType_name = map[int32]string{
		0: "WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED",
		1: "WORKFLOW_INSTANCE_EVENT_TYPE_STARTED",
		2: "WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED",
		3: "WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED",
		4: "WORKFLOW_INSTANCE_EVENT_TYPE_FAILED",
	}
	WorkflowInstanceEventType_value = map[string]int32{
		"WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED": 0,
		"WORKFLOW_INSTANCE_EVENT_TYPE_STARTED":     1,
		"WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED":     2,
		"WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED":   3,
		"WORKFLOW_INSTANCE_EVENT_TYPE_FAILED":      4,
	}
)

func (x WorkflowInstanceEventType) Enum() *WorkflowInstanceEventType {
	p := new(WorkflowInstanceEventType)
	*p = x
	return p
}

func (x WorkflowInstanceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowInstanceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[3].Descriptor()
}

func (WorkflowInstanceEventType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[3]
}

func (x WorkflowInstanceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowInstanceEventType.Descriptor instead.
func (WorkflowInstanceEventType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{3}
}

type WebsocketScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WebsocketScopeType     `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.WebsocketScopeType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketScope) Reset() {
	*x = WebsocketScope{}
	mi := &file_definition_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketScope) ProtoMessage() {}

func (x *WebsocketScope) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketScope.ProtoReflect.Descriptor instead.
func (*WebsocketScope) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketScope) GetType() WebsocketScopeType {
	if x != nil {
		return x.Type
	}
	return WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED
}

func (x *WebsocketScope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WebsocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  WebsocketMessageType   `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.WebsocketMessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebsocketMessage_WorkflowInstanceEvent
	Payload       isWebsocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	mi := &file_definition_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *WebsocketMessage) GetType() WebsocketMessageType {
	if x != nil {
		return x.Type
	}
	return WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED
}

func (x *WebsocketMessage) GetPayload() isWebsocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebsocketMessage) GetWorkflowInstanceEvent() *WorkflowInstanceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_WorkflowInstanceEvent); ok {
			return x.WorkflowInstanceEvent
		}
	}
	return nil
}

type isWebsocketMessage_Payload interface {
	isWebsocketMessage_Payload()
}

type WebsocketMessage_WorkflowInstanceEvent struct {
	WorkflowInstanceEvent *WorkflowInstanceEvent `protobuf:"bytes,2,opt,name=workflow_instance_event,json=workflowInstanceEvent,proto3,oneof"`
}

func (*WebsocketMessage_WorkflowInstanceEvent) isWebsocketMessage_Payload() {}

type WebsocketCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  WebsocketCommandType   `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.WebsocketCommandType" json:"type,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*WebsocketCommand_SubscribeCommand
	//	*WebsocketCommand_UnsubscribeCommand
	Command       isWebsocketCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketCommand) Reset() {
	*x = WebsocketCommand{}
	mi := &file_definition_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketCommand) ProtoMessage() {}

func (x *WebsocketCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketCommand.ProtoReflect.Descriptor instead.
func (*WebsocketCommand) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketCommand) GetType() WebsocketCommandType {
	if x != nil {
		return x.Type
	}
	return WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSPECIFIED
}

func (x *WebsocketCommand) GetCommand() isWebsocketCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WebsocketCommand) GetSubscribeCommand() *WebsocketSubscribeCommand {
	if x != nil {
		if x, ok := x.Command.(*WebsocketCommand_SubscribeCommand); ok {
			return x.SubscribeCommand
		}
	}
	return nil
}

func (x *WebsocketCommand) GetUnsubscribeCommand() *WebsocketUnsubscribeCommand {
	if x != nil {
		if x, ok := x.Command.(*WebsocketCommand_UnsubscribeCommand); ok {
			return x.UnsubscribeCommand
		}
	}
	return nil
}

type isWebsocketCommand_Command interface {
	isWebsocketCommand_Command()
}

type WebsocketCommand_SubscribeCommand struct {
	SubscribeCommand *WebsocketSubscribeCommand `protobuf:"bytes,2,opt,name=subscribe_command,json=subscribeCommand,proto3,oneof"`
}

type WebsocketCommand_UnsubscribeCommand struct {
	UnsubscribeCommand *WebsocketUnsubscribeCommand `protobuf:"bytes,3,opt,name=unsubscribe_command,json=unsubscribeCommand,proto3,oneof"`
}

func (*WebsocketCommand_SubscribeCommand) isWebsocketCommand_Command() {}

func (*WebsocketCommand_UnsubscribeCommand) isWebsocketCommand_Command() {}

type WebsocketSubscribeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeType     WebsocketScopeType     `protobuf:"varint,1,opt,name=scope_type,json=scopeType,proto3,enum=websocket.WebsocketScopeType" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketSubscribeCommand) Reset() {
	*x = WebsocketSubscribeCommand{}
	mi := &file_definition_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketSubscribeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketSubscribeCommand) ProtoMessage() {}

func (x *WebsocketSubscribeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketSubscribeCommand.ProtoReflect.Descriptor instead.
func (*WebsocketSubscribeCommand) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *WebsocketSubscribeCommand) GetScopeType() WebsocketScopeType {
	if x != nil {
		return x.ScopeType
	}
	return WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED
}

func (x *WebsocketSubscribeCommand) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type WebsocketUnsubscribeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeType     WebsocketScopeType     `protobuf:"varint,1,opt,name=scope_type,json=scopeType,proto3,enum=websocket.WebsocketScopeType" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketUnsubscribeCommand) Reset() {
	*x = WebsocketUnsubscribeCommand{}
	mi := &file_definition_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketUnsubscribeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketUnsubscribeCommand) ProtoMessage() {}

func (x *WebsocketUnsubscribeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketUnsubscribeCommand.ProtoReflect.Descriptor instead.
func (*WebsocketUnsubscribeCommand) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *WebsocketUnsubscribeCommand) GetScopeType() WebsocketScopeType {
	if x != nil {
		return x.ScopeType
	}
	return WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED
}

func (x *WebsocketUnsubscribeCommand) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type WorkflowInstanceEvent struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	WorkflowInstanceId string                    `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	EventType          WorkflowInstanceEventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=websocket.WorkflowInstanceEventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*WorkflowInstanceEvent_StartedDetails
	//	*WorkflowInstanceEvent_UpdatedDetails
	//	*WorkflowInstanceEvent_CompletedDetails
	//	*WorkflowInstanceEvent_FailedDetails
	Details       isWorkflowInstanceEvent_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceEvent) Reset() {
	*x = WorkflowInstanceEvent{}
	mi := &file_definition_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceEvent) ProtoMessage() {}

func (x *WorkflowInstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceEvent.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceEvent) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowInstanceEvent) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *WorkflowInstanceEvent) GetEventType() WorkflowInstanceEventType {
	if x != nil {
		return x.EventType
	}
	return WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED
}

func (x *WorkflowInstanceEvent) GetDetails() isWorkflowInstanceEvent_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetStartedDetails() *WorkflowInstanceStartedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_StartedDetails); ok {
			return x.StartedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetUpdatedDetails() *WorkflowInstanceUpdatedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_UpdatedDetails); ok {
			return x.UpdatedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetCompletedDetails() *WorkflowInstanceCompletedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_CompletedDetails); ok {
			return x.CompletedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetFailedDetails() *WorkflowInstanceFailedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_FailedDetails); ok {
			return x.FailedDetails
		}
	}
	return nil
}

type isWorkflowInstanceEvent_Details interface {
	isWorkflowInstanceEvent_Details()
}

type WorkflowInstanceEvent_StartedDetails struct {
	StartedDetails *WorkflowInstanceStartedDetails `protobuf:"bytes,3,opt,name=started_details,json=startedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_UpdatedDetails struct {
	UpdatedDetails *WorkflowInstanceUpdatedDetails `protobuf:"bytes,4,opt,name=updated_details,json=updatedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_CompletedDetails struct {
	CompletedDetails *WorkflowInstanceCompletedDetails `protobuf:"bytes,5,opt,name=completed_details,json=completedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_FailedDetails struct {
	FailedDetails *WorkflowInstanceFailedDetails `protobuf:"bytes,6,opt,name=failed_details,json=failedDetails,proto3,oneof"`
}

func (*WorkflowInstanceEvent_StartedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_UpdatedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_CompletedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_FailedDetails) isWorkflowInstanceEvent_Details() {}

type WorkflowInstanceStartedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceStartedDetails) Reset() {
	*x = WorkflowInstanceStartedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceStartedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceStartedDetails) ProtoMessage() {}

func (x *WorkflowInstanceStartedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceStartedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceStartedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{6}
}

type WorkflowInstanceUpdatedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceUpdatedDetails) Reset() {
	*x = WorkflowInstanceUpdatedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceUpdatedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceUpdatedDetails) ProtoMessage() {}

func (x *WorkflowInstanceUpdatedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceUpdatedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceUpdatedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{7}
}

type WorkflowInstanceCompletedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceCompletedDetails) Reset() {
	*x = WorkflowInstanceCompletedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceCompletedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceCompletedDetails) ProtoMessage() {}

func (x *WorkflowInstanceCompletedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceCompletedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceCompletedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{8}
}

type WorkflowInstanceFailedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceFailedDetails) Reset() {
	*x = WorkflowInstanceFailedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceFailedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceFailedDetails) ProtoMessage() {}

func (x *WorkflowInstanceFailedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceFailedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceFailedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{9}
}

var File_definition_websocket_proto protoreflect.FileDescriptor

const file_definition_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1adefinition/websocket.proto\x12\twebsocket\"S\n" +
	"\x0eWebsocketScope\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.websocket.WebsocketScopeTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xae\x01\n" +
	"\x10WebsocketMessage\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.websocket.WebsocketMessageTypeR\x04type\x12Z\n" +
	"\x17workflow_instance_event\x18\x02 \x01(\v2 .websocket.WorkflowInstanceEventH\x00R\x15workflowInstanceEventB\t\n" +
	"\apayload\"\x82\x02\n" +
	"\x10WebsocketCommand\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.websocket.WebsocketCommandTypeR\x04type\x12S\n" +
	"\x11subscribe_command\x18\x02 \x01(\v2$.websocket.WebsocketSubscribeCommandH\x00R\x10subscribeCommand\x12Y\n" +
	"\x13unsubscribe_command\x18\x03 \x01(\v2&.websocket.WebsocketUnsubscribeCommandH\x00R\x12unsubscribeCommandB\t\n" +
	"\acommand\"t\n" +
	"\x19WebsocketSubscribeCommand\x12<\n" +
	"\n" +
	"scope_type\x18\x01 \x01(\x0e2\x1d.websocket.WebsocketScopeTypeR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\"v\n" +
	"\x1bWebsocketUnsubscribeCommand\x12<\n" +
	"\n" +
	"scope_type\x18\x01 \x01(\x0e2\x1d.websocket.WebsocketScopeTypeR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\"\xf4\x03\n" +
	"\x15WorkflowInstanceEvent\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12C\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2$.websocket.WorkflowInstanceEventTypeR\teventType\x12T\n" +
	"\x0fstarted_details\x18\x03 \x01(\v2).websocket.WorkflowInstanceStartedDetailsH\x00R\x0estartedDetails\x12T\n" +
	"\x0fupdated_details\x18\x04 \x01(\v2).websocket.WorkflowInstanceUpdatedDetailsH\x00R\x0eupdatedDetails\x12Z\n" +
	"\x11completed_details\x18\x05 \x01(\v2+.websocket.WorkflowInstanceCompletedDetailsH\x00R\x10completedDetails\x12Q\n" +
	"\x0efailed_details\x18\x06 \x01(\v2(.websocket.WorkflowInstanceFailedDetailsH\x00R\rfailedDetailsB\t\n" +
	"\adetails\" \n" +
	"\x1eWorkflowInstanceStartedDetails\" \n" +
	"\x1eWorkflowInstanceUpdatedDetails\"\"\n" +
	" WorkflowInstanceCompletedDetails\"\x1f\n" +
	"\x1dWorkflowInstanceFailedDetails*f\n" +
	"\x12WebsocketScopeType\x12$\n" +
	" WEBSOCKET_SCOPE_TYPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE\x10\x01*r\n" +
	"\x14WebsocketMessageType\x12&\n" +
	"\"WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x122\n" +
	".WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT\x10\x01*\x8c\x01\n" +
	"\x14WebsocketCommandType\x12&\n" +
	"\"WEBSOCKET_COMMAND_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" WEBSOCKET_COMMAND_TYPE_SUBSCRIBE\x10\x01\x12&\n" +
	"\"WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE\x10\x02*\xf2\x01\n" +
	"\x19WorkflowInstanceEventType\x12,\n" +
	"(WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$WORKFLOW_INSTANCE_EVENT_TYPE_STARTED\x10\x01\x12(\n" +
	"$WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED\x10\x02\x12*\n" +
	"&WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED\x10\x03\x12'\n" +
	"#WORKFLOW_INSTANCE_EVENT_TYPE_FAILED\x10\x04B\tZ\a./protob\x06proto3"

var (
	file_definition_websocket_proto_rawDescOnce sync.Once
	file_definition_websocket_proto_rawDescData []byte
)

func file_definition_websocket_proto_rawDescGZIP() []byte {
	file_definition_websocket_proto_rawDescOnce.Do(func() {
		file_definition_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definition_websocket_proto_rawDesc), len(file_definition_websocket_proto_rawDesc)))
	})
	return file_definition_websocket_proto_rawDescData
}

var file_definition_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_definition_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_definition_websocket_proto_goTypes = []any{
	(WebsocketScopeType)(0),                  // 0: websocket.WebsocketScopeType
	(WebsocketMessageType)(0),                // 1: websocket.WebsocketMessageType
	(WebsocketCommandType)(0),                // 2: websocket.WebsocketCommandType
	(WorkflowInstanceEventType)(0),           // 3: websocket.WorkflowInstanceEventType
	(*WebsocketScope)(nil),                   // 4: websocket.WebsocketScope
	(*WebsocketMessage)(nil),                 // 5: websocket.WebsocketMessage
	(*WebsocketCommand)(nil),                 // 6: websocket.WebsocketCommand
	(*WebsocketSubscribeCommand)(nil),        // 7: websocket.WebsocketSubscribeCommand
	(*WebsocketUnsubscribeCommand)(nil),      // 8: websocket.WebsocketUnsubscribeCommand
	(*WorkflowInstanceEvent)(nil),            // 9: websocket.WorkflowInstanceEvent
	(*WorkflowInstanceStartedDetails)(nil),   // 10: websocket.WorkflowInstanceStartedDetails
	(*WorkflowInstanceUpdatedDetails)(nil),   // 11: websocket.WorkflowInstanceUpdatedDetails
	(*WorkflowInstanceCompletedDetails)(nil), // 12: websocket.WorkflowInstanceCompletedDetails
	(*WorkflowInstanceFailedDetails)(nil),    // 13: websocket.WorkflowInstanceFailedDetails
}
var file_definition_websocket_proto_depIdxs = []int32{
	0,  // 0: websocket.WebsocketScope.type:type_name -> websocket.WebsocketScopeType
	1,  // 1: websocket.WebsocketMessage.type:type_name -> websocket.WebsocketMessageType
	9,  // 2: websocket.WebsocketMessage.workflow_instance_event:type_name -> websocket.WorkflowInstanceEvent
	2,  // 3: websocket.WebsocketCommand.type:type_name -> websocket.WebsocketCommandType
	7,  // 4: websocket.WebsocketCommand.subscribe_command:type_name -> websocket.WebsocketSubscribeCommand
	8,  // 5: websocket.WebsocketCommand.unsubscribe_command:type_name -> websocket.WebsocketUnsubscribeCommand
	0,  // 6: websocket.WebsocketSubscribeCommand.scope_type:type_name -> websocket.WebsocketScopeType
	0,  // 7: websocket.WebsocketUnsubscribeCommand.scope_type:type_name -> websocket.WebsocketScopeType
	3,  // 8: websocket.WorkflowInstanceEvent.event_type:type_name -> websocket.WorkflowInstanceEventType
	10, // 9: websocket.WorkflowInstanceEvent.started_details:type_name -> websocket.WorkflowInstanceStartedDetails
	11, // 10: websocket.WorkflowInstanceEvent.updated_details:type_name -> websocket.WorkflowInstanceUpdatedDetails
	12, // 11: websocket.WorkflowInstanceEvent.completed_details:type_name -> websocket.WorkflowInstanceCompletedDetails
	13, // 12: websocket.WorkflowInstanceEvent.failed_details:type_name -> websocket.WorkflowInstanceFailedDetails
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_definition_websocket_proto_init() }
func file_definition_websocket_proto_init() {
	if File_definition_websocket_proto != nil {
		return
	}
	file_definition_websocket_proto_msgTypes[1].OneofWrappers = []any{
		(*WebsocketMessage_WorkflowInstanceEvent)(nil),
	}
	file_definition_websocket_proto_msgTypes[2].OneofWrappers = []any{
		(*WebsocketCommand_SubscribeCommand)(nil),
		(*WebsocketCommand_UnsubscribeCommand)(nil),
	}
	file_definition_websocket_proto_msgTypes[5].OneofWrappers = []any{
		(*WorkflowInstanceEvent_StartedDetails)(nil),
		(*WorkflowInstanceEvent_UpdatedDetails)(nil),
		(*WorkflowInstanceEvent_CompletedDetails)(nil),
		(*WorkflowInstanceEvent_FailedDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definition_websocket_proto_rawDesc), len(file_definition_websocket_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_definition_websocket_proto_goTypes,
		DependencyIndexes: file_definition_websocket_proto_depIdxs,
		EnumInfos:         file_definition_websocket_proto_enumTypes,
		MessageInfos:      file_definition_websocket_proto_msgTypes,
	}.Build()
	File_definition_websocket_proto = out.File
	file_definition_websocket_proto_goTypes = nil
	file_definition_websocket_proto_depIdxs = nil
}
