// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: definition/websocket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsocketScopeType int32

const (
	WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED       WebsocketScopeType = 0
	WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE WebsocketScopeType = 1
	WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_TASK_INSTANCE     WebsocketScopeType = 2
)

// Enum value maps for WebsocketScopeType.
var (
	WebsocketScopeType_name = map[int32]string{
		0: "WEBSOCKET_SCOPE_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE",
		2: "WEBSOCKET_SCOPE_TYPE_TASK_INSTANCE",
	}
	WebsocketScopeType_value = map[string]int32{
		"WEBSOCKET_SCOPE_TYPE_UNSPECIFIED":       0,
		"WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE": 1,
		"WEBSOCKET_SCOPE_TYPE_TASK_INSTANCE":     2,
	}
)

func (x WebsocketScopeType) Enum() *WebsocketScopeType {
	p := new(WebsocketScopeType)
	*p = x
	return p
}

func (x WebsocketScopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketScopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[0].Descriptor()
}

func (WebsocketScopeType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[0]
}

func (x WebsocketScopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketScopeType.Descriptor instead.
func (WebsocketScopeType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{0}
}

type WebsocketMessageType int32

const (
	WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED             WebsocketMessageType = 0
	WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT WebsocketMessageType = 1
	WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_CLIENT_REGISTERED       WebsocketMessageType = 2
)

// Enum value maps for WebsocketMessageType.
var (
	WebsocketMessageType_name = map[int32]string{
		0: "WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT",
		2: "WEBSOCKET_MESSAGE_TYPE_CLIENT_REGISTERED",
	}
	WebsocketMessageType_value = map[string]int32{
		"WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED":             0,
		"WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT": 1,
		"WEBSOCKET_MESSAGE_TYPE_CLIENT_REGISTERED":       2,
	}
)

func (x WebsocketMessageType) Enum() *WebsocketMessageType {
	p := new(WebsocketMessageType)
	*p = x
	return p
}

func (x WebsocketMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[1].Descriptor()
}

func (WebsocketMessageType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[1]
}

func (x WebsocketMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketMessageType.Descriptor instead.
func (WebsocketMessageType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{1}
}

type WebsocketCommandType int32

const (
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSPECIFIED WebsocketCommandType = 0
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_SUBSCRIBE   WebsocketCommandType = 1
	WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE WebsocketCommandType = 2
)

// Enum value maps for WebsocketCommandType.
var (
	WebsocketCommandType_name = map[int32]string{
		0: "WEBSOCKET_COMMAND_TYPE_UNSPECIFIED",
		1: "WEBSOCKET_COMMAND_TYPE_SUBSCRIBE",
		2: "WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE",
	}
	WebsocketCommandType_value = map[string]int32{
		"WEBSOCKET_COMMAND_TYPE_UNSPECIFIED": 0,
		"WEBSOCKET_COMMAND_TYPE_SUBSCRIBE":   1,
		"WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE": 2,
	}
)

func (x WebsocketCommandType) Enum() *WebsocketCommandType {
	p := new(WebsocketCommandType)
	*p = x
	return p
}

func (x WebsocketCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebsocketCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[2].Descriptor()
}

func (WebsocketCommandType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[2]
}

func (x WebsocketCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebsocketCommandType.Descriptor instead.
func (WebsocketCommandType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{2}
}

type WorkflowInstanceEventType int32

const (
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED WorkflowInstanceEventType = 0
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_STARTED     WorkflowInstanceEventType = 1
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED     WorkflowInstanceEventType = 2
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED   WorkflowInstanceEventType = 3
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_FAILED      WorkflowInstanceEventType = 4
	WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_CREATED     WorkflowInstanceEventType = 5
)

// Enum value maps for WorkflowInstanceEventType.
var (
	WorkflowInstanceEventType_name = map[int32]string{
		0: "WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED",
		1: "WORKFLOW_INSTANCE_EVENT_TYPE_STARTED",
		2: "WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED",
		3: "WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED",
		4: "WORKFLOW_INSTANCE_EVENT_TYPE_FAILED",
		5: "WORKFLOW_INSTANCE_EVENT_TYPE_CREATED",
	}
	WorkflowInstanceEventType_value = map[string]int32{
		"WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED": 0,
		"WORKFLOW_INSTANCE_EVENT_TYPE_STARTED":     1,
		"WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED":     2,
		"WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED":   3,
		"WORKFLOW_INSTANCE_EVENT_TYPE_FAILED":      4,
		"WORKFLOW_INSTANCE_EVENT_TYPE_CREATED":     5,
	}
)

func (x WorkflowInstanceEventType) Enum() *WorkflowInstanceEventType {
	p := new(WorkflowInstanceEventType)
	*p = x
	return p
}

func (x WorkflowInstanceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowInstanceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[3].Descriptor()
}

func (WorkflowInstanceEventType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[3]
}

func (x WorkflowInstanceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowInstanceEventType.Descriptor instead.
func (WorkflowInstanceEventType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{3}
}

type TaskInstanceEventType int32

const (
	TaskInstanceEventType_TASK_INSTANCE_EVENT_TYPE_UNSPECIFIED TaskInstanceEventType = 0
	TaskInstanceEventType_TASK_INSTANCE_EVENT_TYPE_STARTED     TaskInstanceEventType = 1
	TaskInstanceEventType_TASK_INSTANCE_EVENT_TYPE_COMPLETED   TaskInstanceEventType = 2
	TaskInstanceEventType_TASK_INSTANCE_EVENT_TYPE_FAILED      TaskInstanceEventType = 3
)

// Enum value maps for TaskInstanceEventType.
var (
	TaskInstanceEventType_name = map[int32]string{
		0: "TASK_INSTANCE_EVENT_TYPE_UNSPECIFIED",
		1: "TASK_INSTANCE_EVENT_TYPE_STARTED",
		2: "TASK_INSTANCE_EVENT_TYPE_COMPLETED",
		3: "TASK_INSTANCE_EVENT_TYPE_FAILED",
	}
	TaskInstanceEventType_value = map[string]int32{
		"TASK_INSTANCE_EVENT_TYPE_UNSPECIFIED": 0,
		"TASK_INSTANCE_EVENT_TYPE_STARTED":     1,
		"TASK_INSTANCE_EVENT_TYPE_COMPLETED":   2,
		"TASK_INSTANCE_EVENT_TYPE_FAILED":      3,
	}
)

func (x TaskInstanceEventType) Enum() *TaskInstanceEventType {
	p := new(TaskInstanceEventType)
	*p = x
	return p
}

func (x TaskInstanceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskInstanceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_websocket_proto_enumTypes[4].Descriptor()
}

func (TaskInstanceEventType) Type() protoreflect.EnumType {
	return &file_definition_websocket_proto_enumTypes[4]
}

func (x TaskInstanceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskInstanceEventType.Descriptor instead.
func (TaskInstanceEventType) EnumDescriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{4}
}

type WebsocketScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WebsocketScopeType     `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.WebsocketScopeType" json:"type,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketScope) Reset() {
	*x = WebsocketScope{}
	mi := &file_definition_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketScope) ProtoMessage() {}

func (x *WebsocketScope) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketScope.ProtoReflect.Descriptor instead.
func (*WebsocketScope) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketScope) GetType() WebsocketScopeType {
	if x != nil {
		return x.Type
	}
	return WebsocketScopeType_WEBSOCKET_SCOPE_TYPE_UNSPECIFIED
}

func (x *WebsocketScope) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type WebsocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  WebsocketMessageType   `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.WebsocketMessageType" json:"type,omitempty"`
	Scope *WebsocketScope        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebsocketMessage_WorkflowInstanceEvent
	//	*WebsocketMessage_TaskInstanceEvent
	//	*WebsocketMessage_ClientRegisteredEvent
	Payload       isWebsocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	mi := &file_definition_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *WebsocketMessage) GetType() WebsocketMessageType {
	if x != nil {
		return x.Type
	}
	return WebsocketMessageType_WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED
}

func (x *WebsocketMessage) GetScope() *WebsocketScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *WebsocketMessage) GetPayload() isWebsocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebsocketMessage) GetWorkflowInstanceEvent() *WorkflowInstanceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_WorkflowInstanceEvent); ok {
			return x.WorkflowInstanceEvent
		}
	}
	return nil
}

func (x *WebsocketMessage) GetTaskInstanceEvent() *TaskInstanceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_TaskInstanceEvent); ok {
			return x.TaskInstanceEvent
		}
	}
	return nil
}

func (x *WebsocketMessage) GetClientRegisteredEvent() *ClientRegisteredEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_ClientRegisteredEvent); ok {
			return x.ClientRegisteredEvent
		}
	}
	return nil
}

type isWebsocketMessage_Payload interface {
	isWebsocketMessage_Payload()
}

type WebsocketMessage_WorkflowInstanceEvent struct {
	WorkflowInstanceEvent *WorkflowInstanceEvent `protobuf:"bytes,3,opt,name=workflow_instance_event,json=workflowInstanceEvent,proto3,oneof"`
}

type WebsocketMessage_TaskInstanceEvent struct {
	TaskInstanceEvent *TaskInstanceEvent `protobuf:"bytes,4,opt,name=task_instance_event,json=taskInstanceEvent,proto3,oneof"`
}

type WebsocketMessage_ClientRegisteredEvent struct {
	ClientRegisteredEvent *ClientRegisteredEvent `protobuf:"bytes,5,opt,name=client_registered_event,json=clientRegisteredEvent,proto3,oneof"`
}

func (*WebsocketMessage_WorkflowInstanceEvent) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_TaskInstanceEvent) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_ClientRegisteredEvent) isWebsocketMessage_Payload() {}

type WebsocketCommand struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Type     WebsocketCommandType   `protobuf:"varint,2,opt,name=type,proto3,enum=websocket.WebsocketCommandType" json:"type,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*WebsocketCommand_SubscribeCommand
	Command       isWebsocketCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketCommand) Reset() {
	*x = WebsocketCommand{}
	mi := &file_definition_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketCommand) ProtoMessage() {}

func (x *WebsocketCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketCommand.ProtoReflect.Descriptor instead.
func (*WebsocketCommand) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketCommand) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WebsocketCommand) GetType() WebsocketCommandType {
	if x != nil {
		return x.Type
	}
	return WebsocketCommandType_WEBSOCKET_COMMAND_TYPE_UNSPECIFIED
}

func (x *WebsocketCommand) GetCommand() isWebsocketCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WebsocketCommand) GetSubscribeCommand() *WebsocketSubscribeCommand {
	if x != nil {
		if x, ok := x.Command.(*WebsocketCommand_SubscribeCommand); ok {
			return x.SubscribeCommand
		}
	}
	return nil
}

type isWebsocketCommand_Command interface {
	isWebsocketCommand_Command()
}

type WebsocketCommand_SubscribeCommand struct {
	SubscribeCommand *WebsocketSubscribeCommand `protobuf:"bytes,3,opt,name=subscribe_command,json=subscribeCommand,proto3,oneof"`
}

func (*WebsocketCommand_SubscribeCommand) isWebsocketCommand_Command() {}

type WebsocketSubscribeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []*WebsocketScope      `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketSubscribeCommand) Reset() {
	*x = WebsocketSubscribeCommand{}
	mi := &file_definition_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketSubscribeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketSubscribeCommand) ProtoMessage() {}

func (x *WebsocketSubscribeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketSubscribeCommand.ProtoReflect.Descriptor instead.
func (*WebsocketSubscribeCommand) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *WebsocketSubscribeCommand) GetScopes() []*WebsocketScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type WorkflowInstanceEvent struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	WorkflowInstanceId string                    `protobuf:"bytes,1,opt,name=workflow_instance_id,json=workflowInstanceId,proto3" json:"workflow_instance_id,omitempty"`
	EventType          WorkflowInstanceEventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=websocket.WorkflowInstanceEventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*WorkflowInstanceEvent_StartedDetails
	//	*WorkflowInstanceEvent_UpdatedDetails
	//	*WorkflowInstanceEvent_CompletedDetails
	//	*WorkflowInstanceEvent_FailedDetails
	//	*WorkflowInstanceEvent_CreatedDetails
	Details       isWorkflowInstanceEvent_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceEvent) Reset() {
	*x = WorkflowInstanceEvent{}
	mi := &file_definition_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceEvent) ProtoMessage() {}

func (x *WorkflowInstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceEvent.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceEvent) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowInstanceEvent) GetWorkflowInstanceId() string {
	if x != nil {
		return x.WorkflowInstanceId
	}
	return ""
}

func (x *WorkflowInstanceEvent) GetEventType() WorkflowInstanceEventType {
	if x != nil {
		return x.EventType
	}
	return WorkflowInstanceEventType_WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED
}

func (x *WorkflowInstanceEvent) GetDetails() isWorkflowInstanceEvent_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetStartedDetails() *WorkflowInstanceStartedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_StartedDetails); ok {
			return x.StartedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetUpdatedDetails() *WorkflowInstanceUpdatedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_UpdatedDetails); ok {
			return x.UpdatedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetCompletedDetails() *WorkflowInstanceCompletedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_CompletedDetails); ok {
			return x.CompletedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetFailedDetails() *WorkflowInstanceFailedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_FailedDetails); ok {
			return x.FailedDetails
		}
	}
	return nil
}

func (x *WorkflowInstanceEvent) GetCreatedDetails() *WorkflowInstanceCreatedDetails {
	if x != nil {
		if x, ok := x.Details.(*WorkflowInstanceEvent_CreatedDetails); ok {
			return x.CreatedDetails
		}
	}
	return nil
}

type isWorkflowInstanceEvent_Details interface {
	isWorkflowInstanceEvent_Details()
}

type WorkflowInstanceEvent_StartedDetails struct {
	StartedDetails *WorkflowInstanceStartedDetails `protobuf:"bytes,3,opt,name=started_details,json=startedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_UpdatedDetails struct {
	UpdatedDetails *WorkflowInstanceUpdatedDetails `protobuf:"bytes,4,opt,name=updated_details,json=updatedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_CompletedDetails struct {
	CompletedDetails *WorkflowInstanceCompletedDetails `protobuf:"bytes,5,opt,name=completed_details,json=completedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_FailedDetails struct {
	FailedDetails *WorkflowInstanceFailedDetails `protobuf:"bytes,6,opt,name=failed_details,json=failedDetails,proto3,oneof"`
}

type WorkflowInstanceEvent_CreatedDetails struct {
	CreatedDetails *WorkflowInstanceCreatedDetails `protobuf:"bytes,7,opt,name=created_details,json=createdDetails,proto3,oneof"`
}

func (*WorkflowInstanceEvent_StartedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_UpdatedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_CompletedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_FailedDetails) isWorkflowInstanceEvent_Details() {}

func (*WorkflowInstanceEvent_CreatedDetails) isWorkflowInstanceEvent_Details() {}

type WorkflowInstanceStartedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceStartedDetails) Reset() {
	*x = WorkflowInstanceStartedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceStartedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceStartedDetails) ProtoMessage() {}

func (x *WorkflowInstanceStartedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceStartedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceStartedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{5}
}

type WorkflowInstanceUpdatedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceUpdatedDetails) Reset() {
	*x = WorkflowInstanceUpdatedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceUpdatedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceUpdatedDetails) ProtoMessage() {}

func (x *WorkflowInstanceUpdatedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceUpdatedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceUpdatedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{6}
}

type WorkflowInstanceCompletedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceCompletedDetails) Reset() {
	*x = WorkflowInstanceCompletedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceCompletedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceCompletedDetails) ProtoMessage() {}

func (x *WorkflowInstanceCompletedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceCompletedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceCompletedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{7}
}

type WorkflowInstanceFailedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceFailedDetails) Reset() {
	*x = WorkflowInstanceFailedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceFailedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceFailedDetails) ProtoMessage() {}

func (x *WorkflowInstanceFailedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceFailedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceFailedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{8}
}

type WorkflowInstanceCreatedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceCreatedDetails) Reset() {
	*x = WorkflowInstanceCreatedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceCreatedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceCreatedDetails) ProtoMessage() {}

func (x *WorkflowInstanceCreatedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceCreatedDetails.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceCreatedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{9}
}

type TaskInstanceEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskInstanceId string                 `protobuf:"bytes,1,opt,name=task_instance_id,json=taskInstanceId,proto3" json:"task_instance_id,omitempty"`
	EventType      TaskInstanceEventType  `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=websocket.TaskInstanceEventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*TaskInstanceEvent_StartedDetails
	//	*TaskInstanceEvent_CompletedDetails
	//	*TaskInstanceEvent_FailedDetails
	Details       isTaskInstanceEvent_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInstanceEvent) Reset() {
	*x = TaskInstanceEvent{}
	mi := &file_definition_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInstanceEvent) ProtoMessage() {}

func (x *TaskInstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInstanceEvent.ProtoReflect.Descriptor instead.
func (*TaskInstanceEvent) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{10}
}

func (x *TaskInstanceEvent) GetTaskInstanceId() string {
	if x != nil {
		return x.TaskInstanceId
	}
	return ""
}

func (x *TaskInstanceEvent) GetEventType() TaskInstanceEventType {
	if x != nil {
		return x.EventType
	}
	return TaskInstanceEventType_TASK_INSTANCE_EVENT_TYPE_UNSPECIFIED
}

func (x *TaskInstanceEvent) GetDetails() isTaskInstanceEvent_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *TaskInstanceEvent) GetStartedDetails() *TaskInstanceStartedDetails {
	if x != nil {
		if x, ok := x.Details.(*TaskInstanceEvent_StartedDetails); ok {
			return x.StartedDetails
		}
	}
	return nil
}

func (x *TaskInstanceEvent) GetCompletedDetails() *TaskInstanceCompletedDetails {
	if x != nil {
		if x, ok := x.Details.(*TaskInstanceEvent_CompletedDetails); ok {
			return x.CompletedDetails
		}
	}
	return nil
}

func (x *TaskInstanceEvent) GetFailedDetails() *TaskInstanceFailedDetails {
	if x != nil {
		if x, ok := x.Details.(*TaskInstanceEvent_FailedDetails); ok {
			return x.FailedDetails
		}
	}
	return nil
}

type isTaskInstanceEvent_Details interface {
	isTaskInstanceEvent_Details()
}

type TaskInstanceEvent_StartedDetails struct {
	StartedDetails *TaskInstanceStartedDetails `protobuf:"bytes,3,opt,name=started_details,json=startedDetails,proto3,oneof"`
}

type TaskInstanceEvent_CompletedDetails struct {
	CompletedDetails *TaskInstanceCompletedDetails `protobuf:"bytes,4,opt,name=completed_details,json=completedDetails,proto3,oneof"`
}

type TaskInstanceEvent_FailedDetails struct {
	FailedDetails *TaskInstanceFailedDetails `protobuf:"bytes,5,opt,name=failed_details,json=failedDetails,proto3,oneof"`
}

func (*TaskInstanceEvent_StartedDetails) isTaskInstanceEvent_Details() {}

func (*TaskInstanceEvent_CompletedDetails) isTaskInstanceEvent_Details() {}

func (*TaskInstanceEvent_FailedDetails) isTaskInstanceEvent_Details() {}

type TaskInstanceStartedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInstanceStartedDetails) Reset() {
	*x = TaskInstanceStartedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInstanceStartedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInstanceStartedDetails) ProtoMessage() {}

func (x *TaskInstanceStartedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInstanceStartedDetails.ProtoReflect.Descriptor instead.
func (*TaskInstanceStartedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{11}
}

type TaskInstanceCompletedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInstanceCompletedDetails) Reset() {
	*x = TaskInstanceCompletedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInstanceCompletedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInstanceCompletedDetails) ProtoMessage() {}

func (x *TaskInstanceCompletedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInstanceCompletedDetails.ProtoReflect.Descriptor instead.
func (*TaskInstanceCompletedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{12}
}

type TaskInstanceFailedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInstanceFailedDetails) Reset() {
	*x = TaskInstanceFailedDetails{}
	mi := &file_definition_websocket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInstanceFailedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInstanceFailedDetails) ProtoMessage() {}

func (x *TaskInstanceFailedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInstanceFailedDetails.ProtoReflect.Descriptor instead.
func (*TaskInstanceFailedDetails) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{13}
}

type ClientRegisteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegisteredEvent) Reset() {
	*x = ClientRegisteredEvent{}
	mi := &file_definition_websocket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisteredEvent) ProtoMessage() {}

func (x *ClientRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_definition_websocket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisteredEvent.ProtoReflect.Descriptor instead.
func (*ClientRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_definition_websocket_proto_rawDescGZIP(), []int{14}
}

func (x *ClientRegisteredEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_definition_websocket_proto protoreflect.FileDescriptor

const file_definition_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1adefinition/websocket.proto\x12\twebsocket\"_\n" +
	"\x0eWebsocketScope\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.websocket.WebsocketScopeTypeR\x04type\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"\x8b\x03\n" +
	"\x10WebsocketMessage\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.websocket.WebsocketMessageTypeR\x04type\x12/\n" +
	"\x05scope\x18\x02 \x01(\v2\x19.websocket.WebsocketScopeR\x05scope\x12Z\n" +
	"\x17workflow_instance_event\x18\x03 \x01(\v2 .websocket.WorkflowInstanceEventH\x00R\x15workflowInstanceEvent\x12N\n" +
	"\x13task_instance_event\x18\x04 \x01(\v2\x1c.websocket.TaskInstanceEventH\x00R\x11taskInstanceEvent\x12Z\n" +
	"\x17client_registered_event\x18\x05 \x01(\v2 .websocket.ClientRegisteredEventH\x00R\x15clientRegisteredEventB\t\n" +
	"\apayload\"\xc4\x01\n" +
	"\x10WebsocketCommand\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.websocket.WebsocketCommandTypeR\x04type\x12S\n" +
	"\x11subscribe_command\x18\x03 \x01(\v2$.websocket.WebsocketSubscribeCommandH\x00R\x10subscribeCommandB\t\n" +
	"\acommand\"N\n" +
	"\x19WebsocketSubscribeCommand\x121\n" +
	"\x06scopes\x18\x01 \x03(\v2\x19.websocket.WebsocketScopeR\x06scopes\"\xca\x04\n" +
	"\x15WorkflowInstanceEvent\x120\n" +
	"\x14workflow_instance_id\x18\x01 \x01(\tR\x12workflowInstanceId\x12C\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2$.websocket.WorkflowInstanceEventTypeR\teventType\x12T\n" +
	"\x0fstarted_details\x18\x03 \x01(\v2).websocket.WorkflowInstanceStartedDetailsH\x00R\x0estartedDetails\x12T\n" +
	"\x0fupdated_details\x18\x04 \x01(\v2).websocket.WorkflowInstanceUpdatedDetailsH\x00R\x0eupdatedDetails\x12Z\n" +
	"\x11completed_details\x18\x05 \x01(\v2+.websocket.WorkflowInstanceCompletedDetailsH\x00R\x10completedDetails\x12Q\n" +
	"\x0efailed_details\x18\x06 \x01(\v2(.websocket.WorkflowInstanceFailedDetailsH\x00R\rfailedDetails\x12T\n" +
	"\x0fcreated_details\x18\a \x01(\v2).websocket.WorkflowInstanceCreatedDetailsH\x00R\x0ecreatedDetailsB\t\n" +
	"\adetails\" \n" +
	"\x1eWorkflowInstanceStartedDetails\" \n" +
	"\x1eWorkflowInstanceUpdatedDetails\"\"\n" +
	" WorkflowInstanceCompletedDetails\"\x1f\n" +
	"\x1dWorkflowInstanceFailedDetails\" \n" +
	"\x1eWorkflowInstanceCreatedDetails\"\x82\x03\n" +
	"\x11TaskInstanceEvent\x12(\n" +
	"\x10task_instance_id\x18\x01 \x01(\tR\x0etaskInstanceId\x12?\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2 .websocket.TaskInstanceEventTypeR\teventType\x12P\n" +
	"\x0fstarted_details\x18\x03 \x01(\v2%.websocket.TaskInstanceStartedDetailsH\x00R\x0estartedDetails\x12V\n" +
	"\x11completed_details\x18\x04 \x01(\v2'.websocket.TaskInstanceCompletedDetailsH\x00R\x10completedDetails\x12M\n" +
	"\x0efailed_details\x18\x05 \x01(\v2$.websocket.TaskInstanceFailedDetailsH\x00R\rfailedDetailsB\t\n" +
	"\adetails\"\x1c\n" +
	"\x1aTaskInstanceStartedDetails\"\x1e\n" +
	"\x1cTaskInstanceCompletedDetails\"\x1b\n" +
	"\x19TaskInstanceFailedDetails\"4\n" +
	"\x15ClientRegisteredEvent\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId*\x8e\x01\n" +
	"\x12WebsocketScopeType\x12$\n" +
	" WEBSOCKET_SCOPE_TYPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&WEBSOCKET_SCOPE_TYPE_WORKFLOW_INSTANCE\x10\x01\x12&\n" +
	"\"WEBSOCKET_SCOPE_TYPE_TASK_INSTANCE\x10\x02*\xa0\x01\n" +
	"\x14WebsocketMessageType\x12&\n" +
	"\"WEBSOCKET_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x122\n" +
	".WEBSOCKET_MESSAGE_TYPE_WORKFLOW_INSTANCE_EVENT\x10\x01\x12,\n" +
	"(WEBSOCKET_MESSAGE_TYPE_CLIENT_REGISTERED\x10\x02*\x8c\x01\n" +
	"\x14WebsocketCommandType\x12&\n" +
	"\"WEBSOCKET_COMMAND_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" WEBSOCKET_COMMAND_TYPE_SUBSCRIBE\x10\x01\x12&\n" +
	"\"WEBSOCKET_COMMAND_TYPE_UNSUBSCRIBE\x10\x02*\x9c\x02\n" +
	"\x19WorkflowInstanceEventType\x12,\n" +
	"(WORKFLOW_INSTANCE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$WORKFLOW_INSTANCE_EVENT_TYPE_STARTED\x10\x01\x12(\n" +
	"$WORKFLOW_INSTANCE_EVENT_TYPE_UPDATED\x10\x02\x12*\n" +
	"&WORKFLOW_INSTANCE_EVENT_TYPE_COMPLETED\x10\x03\x12'\n" +
	"#WORKFLOW_INSTANCE_EVENT_TYPE_FAILED\x10\x04\x12(\n" +
	"$WORKFLOW_INSTANCE_EVENT_TYPE_CREATED\x10\x05*\xb4\x01\n" +
	"\x15TaskInstanceEventType\x12(\n" +
	"$TASK_INSTANCE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" TASK_INSTANCE_EVENT_TYPE_STARTED\x10\x01\x12&\n" +
	"\"TASK_INSTANCE_EVENT_TYPE_COMPLETED\x10\x02\x12#\n" +
	"\x1fTASK_INSTANCE_EVENT_TYPE_FAILED\x10\x03B\tZ\a./protob\x06proto3"

var (
	file_definition_websocket_proto_rawDescOnce sync.Once
	file_definition_websocket_proto_rawDescData []byte
)

func file_definition_websocket_proto_rawDescGZIP() []byte {
	file_definition_websocket_proto_rawDescOnce.Do(func() {
		file_definition_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definition_websocket_proto_rawDesc), len(file_definition_websocket_proto_rawDesc)))
	})
	return file_definition_websocket_proto_rawDescData
}

var file_definition_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_definition_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_definition_websocket_proto_goTypes = []any{
	(WebsocketScopeType)(0),                  // 0: websocket.WebsocketScopeType
	(WebsocketMessageType)(0),                // 1: websocket.WebsocketMessageType
	(WebsocketCommandType)(0),                // 2: websocket.WebsocketCommandType
	(WorkflowInstanceEventType)(0),           // 3: websocket.WorkflowInstanceEventType
	(TaskInstanceEventType)(0),               // 4: websocket.TaskInstanceEventType
	(*WebsocketScope)(nil),                   // 5: websocket.WebsocketScope
	(*WebsocketMessage)(nil),                 // 6: websocket.WebsocketMessage
	(*WebsocketCommand)(nil),                 // 7: websocket.WebsocketCommand
	(*WebsocketSubscribeCommand)(nil),        // 8: websocket.WebsocketSubscribeCommand
	(*WorkflowInstanceEvent)(nil),            // 9: websocket.WorkflowInstanceEvent
	(*WorkflowInstanceStartedDetails)(nil),   // 10: websocket.WorkflowInstanceStartedDetails
	(*WorkflowInstanceUpdatedDetails)(nil),   // 11: websocket.WorkflowInstanceUpdatedDetails
	(*WorkflowInstanceCompletedDetails)(nil), // 12: websocket.WorkflowInstanceCompletedDetails
	(*WorkflowInstanceFailedDetails)(nil),    // 13: websocket.WorkflowInstanceFailedDetails
	(*WorkflowInstanceCreatedDetails)(nil),   // 14: websocket.WorkflowInstanceCreatedDetails
	(*TaskInstanceEvent)(nil),                // 15: websocket.TaskInstanceEvent
	(*TaskInstanceStartedDetails)(nil),       // 16: websocket.TaskInstanceStartedDetails
	(*TaskInstanceCompletedDetails)(nil),     // 17: websocket.TaskInstanceCompletedDetails
	(*TaskInstanceFailedDetails)(nil),        // 18: websocket.TaskInstanceFailedDetails
	(*ClientRegisteredEvent)(nil),            // 19: websocket.ClientRegisteredEvent
}
var file_definition_websocket_proto_depIdxs = []int32{
	0,  // 0: websocket.WebsocketScope.type:type_name -> websocket.WebsocketScopeType
	1,  // 1: websocket.WebsocketMessage.type:type_name -> websocket.WebsocketMessageType
	5,  // 2: websocket.WebsocketMessage.scope:type_name -> websocket.WebsocketScope
	9,  // 3: websocket.WebsocketMessage.workflow_instance_event:type_name -> websocket.WorkflowInstanceEvent
	15, // 4: websocket.WebsocketMessage.task_instance_event:type_name -> websocket.TaskInstanceEvent
	19, // 5: websocket.WebsocketMessage.client_registered_event:type_name -> websocket.ClientRegisteredEvent
	2,  // 6: websocket.WebsocketCommand.type:type_name -> websocket.WebsocketCommandType
	8,  // 7: websocket.WebsocketCommand.subscribe_command:type_name -> websocket.WebsocketSubscribeCommand
	5,  // 8: websocket.WebsocketSubscribeCommand.scopes:type_name -> websocket.WebsocketScope
	3,  // 9: websocket.WorkflowInstanceEvent.event_type:type_name -> websocket.WorkflowInstanceEventType
	10, // 10: websocket.WorkflowInstanceEvent.started_details:type_name -> websocket.WorkflowInstanceStartedDetails
	11, // 11: websocket.WorkflowInstanceEvent.updated_details:type_name -> websocket.WorkflowInstanceUpdatedDetails
	12, // 12: websocket.WorkflowInstanceEvent.completed_details:type_name -> websocket.WorkflowInstanceCompletedDetails
	13, // 13: websocket.WorkflowInstanceEvent.failed_details:type_name -> websocket.WorkflowInstanceFailedDetails
	14, // 14: websocket.WorkflowInstanceEvent.created_details:type_name -> websocket.WorkflowInstanceCreatedDetails
	4,  // 15: websocket.TaskInstanceEvent.event_type:type_name -> websocket.TaskInstanceEventType
	16, // 16: websocket.TaskInstanceEvent.started_details:type_name -> websocket.TaskInstanceStartedDetails
	17, // 17: websocket.TaskInstanceEvent.completed_details:type_name -> websocket.TaskInstanceCompletedDetails
	18, // 18: websocket.TaskInstanceEvent.failed_details:type_name -> websocket.TaskInstanceFailedDetails
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_definition_websocket_proto_init() }
func file_definition_websocket_proto_init() {
	if File_definition_websocket_proto != nil {
		return
	}
	file_definition_websocket_proto_msgTypes[0].OneofWrappers = []any{}
	file_definition_websocket_proto_msgTypes[1].OneofWrappers = []any{
		(*WebsocketMessage_WorkflowInstanceEvent)(nil),
		(*WebsocketMessage_TaskInstanceEvent)(nil),
		(*WebsocketMessage_ClientRegisteredEvent)(nil),
	}
	file_definition_websocket_proto_msgTypes[2].OneofWrappers = []any{
		(*WebsocketCommand_SubscribeCommand)(nil),
	}
	file_definition_websocket_proto_msgTypes[4].OneofWrappers = []any{
		(*WorkflowInstanceEvent_StartedDetails)(nil),
		(*WorkflowInstanceEvent_UpdatedDetails)(nil),
		(*WorkflowInstanceEvent_CompletedDetails)(nil),
		(*WorkflowInstanceEvent_FailedDetails)(nil),
		(*WorkflowInstanceEvent_CreatedDetails)(nil),
	}
	file_definition_websocket_proto_msgTypes[10].OneofWrappers = []any{
		(*TaskInstanceEvent_StartedDetails)(nil),
		(*TaskInstanceEvent_CompletedDetails)(nil),
		(*TaskInstanceEvent_FailedDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definition_websocket_proto_rawDesc), len(file_definition_websocket_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_definition_websocket_proto_goTypes,
		DependencyIndexes: file_definition_websocket_proto_depIdxs,
		EnumInfos:         file_definition_websocket_proto_enumTypes,
		MessageInfos:      file_definition_websocket_proto_msgTypes,
	}.Build()
	File_definition_websocket_proto = out.File
	file_definition_websocket_proto_goTypes = nil
	file_definition_websocket_proto_depIdxs = nil
}
