// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents": {
            "get": {
                "description": "Get a list of all registered agents",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get all agents",
                "operationId": "getAllAgents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/AgentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/agents/{name}": {
            "get": {
                "description": "Get details of a registered agent by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get agent by name",
                "operationId": "getAgentByName",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/step-instances": {
            "get": {
                "description": "Get all step instances with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StepInstances"
                ],
                "summary": "Get all step instances",
                "operationId": "getAllStepInstances",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/StepInstance"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/step-instances/{id}": {
            "get": {
                "description": "Get a step instance by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StepInstances"
                ],
                "summary": "Get step instance by ID",
                "operationId": "getStepInstanceById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Step Instance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/StepInstance"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/task-definitions": {
            "get": {
                "description": "Get all task definitions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task Definitions"
                ],
                "summary": "Get all task definitions",
                "operationId": "getAllTaskDefinitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TaskDefinitionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}": {
            "get": {
                "description": "Get task definition by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task Definitions"
                ],
                "summary": "Get task definition by ID",
                "operationId": "getTaskDefinitionById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TaskDefinitionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/workflow-definitions": {
            "get": {
                "description": "Get all workflow definitions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Get all workflow definitions",
                "operationId": "getAllWorkflowDefinitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/WorkflowDefinition"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new workflow definition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Create a new workflow definition",
                "operationId": "createWorkflowDefinition",
                "parameters": [
                    {
                        "description": "Workflow Definition",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkflowDefinition"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/WorkflowDefinition"
                        }
                    }
                }
            }
        },
        "/workflow-definitions/{id}": {
            "get": {
                "description": "Get a workflow definition by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Get a workflow definition by ID",
                "operationId": "getWorkflowDefinitionByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkflowDefinition"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing workflow definition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Update an existing workflow definition",
                "operationId": "updateWorkflowDefinition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Workflow Definition",
                        "name": "definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateWorkflowDefRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkflowDefinition"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a workflow definition",
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Delete a workflow definition",
                "operationId": "deleteWorkflowDefinition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/workflow-definitions/{id}/disable": {
            "patch": {
                "description": "Delete a workflow definition",
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Delete a workflow definition",
                "operationId": "disableWorkflowDefinition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/workflow-definitions/{id}/enable": {
            "patch": {
                "description": "Delete a workflow definition",
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Delete a workflow definition",
                "operationId": "enableWorkflowDefinition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/workflow-definitions/{id}/publish": {
            "patch": {
                "description": "Publish a workflow definition",
                "tags": [
                    "Workflow Definitions"
                ],
                "summary": "Publish a workflow definition",
                "operationId": "publishWorkflowDefinition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/workflow-instances": {
            "get": {
                "description": "Get all workflow instances",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Instances"
                ],
                "summary": "Get all workflow instances",
                "operationId": "getAllWorkflowInstances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/WorkflowInstance"
                            }
                        }
                    }
                }
            }
        },
        "/workflow-instances/{id}": {
            "get": {
                "description": "Get a workflow instance by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workflow Instances"
                ],
                "summary": "Get a workflow instance by ID",
                "operationId": "getWorkflowInstanceByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow Instance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkflowInstance"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AgentProtocol": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "AgentProtocol_UNKNOWN",
                "AgentProtocol_GRPC",
                "AgentProtocol_HTTP"
            ]
        },
        "AgentResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol": {
                    "$ref": "#/definitions/AgentProtocol"
                },
                "supportedTasks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "DecisionCase": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nextStepId": {
                    "type": "string"
                }
            }
        },
        "DecisionConfig": {
            "type": "object",
            "properties": {
                "cases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DecisionCase"
                    }
                }
            }
        },
        "ForkBranch": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nextStepId": {
                    "type": "string"
                }
            }
        },
        "ForkConfig": {
            "type": "object",
            "properties": {
                "branches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ForkBranch"
                    }
                }
            }
        },
        "JoinConfig": {
            "type": "object",
            "properties": {
                "incomingStepIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nextStepId": {
                    "type": "string"
                }
            }
        },
        "StepDefinitionParameter": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/StepParameterType"
                },
                "value": {}
            }
        },
        "StepDefinitionParameters": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/StepDefinitionParameter"
            }
        },
        "StepInstance": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "output": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "progress": {
                    "type": "number"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/StepStatus"
                },
                "stepId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "workflowDefinitionId": {
                    "type": "string"
                },
                "workflowInstanceId": {
                    "type": "string"
                }
            }
        },
        "StepParameterType": {
            "type": "string",
            "enum": [
                "constant",
                "workflow",
                "taskOutput"
            ],
            "x-enum-varnames": [
                "StepParameterTypeConstant",
                "StepParameterTypeWorkflow",
                "StepParameterTypeTaskOutput"
            ]
        },
        "StepStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StepStatusPending",
                "StepStatusRunning",
                "StepStatusCompleted",
                "StepStatusFailed",
                "StepStatusCancelled"
            ]
        },
        "StepType": {
            "type": "string",
            "enum": [
                "task",
                "workflow",
                "wait",
                "decision",
                "fork",
                "join"
            ],
            "x-enum-varnames": [
                "StepTypeTask",
                "StepTypeWorkflow",
                "StepTypeWait",
                "StepTypeDecision",
                "StepTypeFork",
                "StepTypeJoin"
            ]
        },
        "TaskConfig": {
            "type": "object",
            "properties": {
                "nextStepId": {
                    "type": "string"
                },
                "taskDefinitionId": {
                    "type": "string"
                }
            }
        },
        "TaskDefinitionResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputParameters": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "name": {
                    "type": "string"
                },
                "outputParameters": {
                    "$ref": "#/definitions/UnknownJson"
                }
            }
        },
        "UnknownJson": {
            "type": "object",
            "additionalProperties": true
        },
        "UpdateWorkflowDefRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkflowStepDefinition"
                    }
                }
            }
        },
        "WaitConfig": {
            "type": "object",
            "properties": {
                "durationSeconds": {
                    "$ref": "#/definitions/StepDefinitionParameter"
                },
                "nextStepId": {
                    "type": "string"
                }
            }
        },
        "WorkflowConfig": {
            "type": "object",
            "properties": {
                "nextStepId": {
                    "type": "string"
                },
                "workflowDefinitionId": {
                    "type": "string"
                }
            }
        },
        "WorkflowDefinition": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputParameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkflowParameterDefinition"
                    }
                },
                "isDraft": {
                    "type": "boolean"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "metadata": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "name": {
                    "type": "string"
                },
                "outputParameters": {},
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkflowStepDefinition"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "WorkflowInstance": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "output": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/WorkflowStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "workflowDefinitionId": {
                    "type": "string"
                }
            }
        },
        "WorkflowParameterDefinition": {
            "type": "object",
            "properties": {
                "default": {},
                "description": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "name": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "WorkflowStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED"
            ],
            "x-enum-varnames": [
                "WorkflowStatusPending",
                "WorkflowStatusRunning",
                "WorkflowStatusCompleted",
                "WorkflowStatusFailed",
                "WorkflowStatusCancelled"
            ]
        },
        "WorkflowStepDefinition": {
            "type": "object",
            "properties": {
                "decisionConfig": {
                    "$ref": "#/definitions/DecisionConfig"
                },
                "description": {
                    "type": "string"
                },
                "forkConfig": {
                    "$ref": "#/definitions/ForkConfig"
                },
                "joinConfig": {
                    "$ref": "#/definitions/JoinConfig"
                },
                "metadata": {
                    "$ref": "#/definitions/UnknownJson"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "$ref": "#/definitions/StepDefinitionParameters"
                },
                "stepDefinitionId": {
                    "type": "string"
                },
                "taskConfig": {
                    "$ref": "#/definitions/TaskConfig"
                },
                "type": {
                    "$ref": "#/definitions/StepType"
                },
                "waitConfig": {
                    "$ref": "#/definitions/WaitConfig"
                },
                "workflowConfig": {
                    "$ref": "#/definitions/WorkflowConfig"
                }
            }
        },
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Workflow Engine API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
