/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentProtocol } from './AgentProtocol';
import {
    AgentProtocolFromJSON,
    AgentProtocolFromJSONTyped,
    AgentProtocolToJSON,
    AgentProtocolToJSONTyped,
} from './AgentProtocol';

/**
 * 
 * @export
 * @interface AgentResponse
 */
export interface AgentResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    port?: string;
    /**
     * 
     * @type {AgentProtocol}
     * @memberof AgentResponse
     */
    protocol?: AgentProtocol;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentResponse
     */
    supportedTasks?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    version?: string;
}



/**
 * Check if a given object implements the AgentResponse interface.
 */
export function instanceOfAgentResponse(value: object): value is AgentResponse {
    return true;
}

export function AgentResponseFromJSON(json: any): AgentResponse {
    return AgentResponseFromJSONTyped(json, false);
}

export function AgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'name': json['name'] == null ? undefined : json['name'],
        'port': json['port'] == null ? undefined : json['port'],
        'protocol': json['protocol'] == null ? undefined : AgentProtocolFromJSON(json['protocol']),
        'supportedTasks': json['supportedTasks'] == null ? undefined : json['supportedTasks'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function AgentResponseToJSON(json: any): AgentResponse {
    return AgentResponseToJSONTyped(json, false);
}

export function AgentResponseToJSONTyped(value?: AgentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'name': value['name'],
        'port': value['port'],
        'protocol': AgentProtocolToJSON(value['protocol']),
        'supportedTasks': value['supportedTasks'],
        'version': value['version'],
    };
}

