/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentTaskOverviewResponse
 */
export interface AgentTaskOverviewResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentTaskOverviewResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentTaskOverviewResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentTaskOverviewResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the AgentTaskOverviewResponse interface.
 */
export function instanceOfAgentTaskOverviewResponse(value: object): value is AgentTaskOverviewResponse {
    return true;
}

export function AgentTaskOverviewResponseFromJSON(json: any): AgentTaskOverviewResponse {
    return AgentTaskOverviewResponseFromJSONTyped(json, false);
}

export function AgentTaskOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTaskOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AgentTaskOverviewResponseToJSON(json: any): AgentTaskOverviewResponse {
    return AgentTaskOverviewResponseToJSONTyped(json, false);
}

export function AgentTaskOverviewResponseToJSONTyped(value?: AgentTaskOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

