/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentTaskOverviewResponse } from './AgentTaskOverviewResponse';
import {
    AgentTaskOverviewResponseFromJSON,
    AgentTaskOverviewResponseFromJSONTyped,
    AgentTaskOverviewResponseToJSON,
    AgentTaskOverviewResponseToJSONTyped,
} from './AgentTaskOverviewResponse';

/**
 * 
 * @export
 * @interface AgentOverviewResponse
 */
export interface AgentOverviewResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentOverviewResponse
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentOverviewResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentOverviewResponse
     */
    port?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentOverviewResponse
     */
    protocol?: string;
    /**
     * 
     * @type {Array<AgentTaskOverviewResponse>}
     * @memberof AgentOverviewResponse
     */
    tasks?: Array<AgentTaskOverviewResponse>;
    /**
     * 
     * @type {string}
     * @memberof AgentOverviewResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the AgentOverviewResponse interface.
 */
export function instanceOfAgentOverviewResponse(value: object): value is AgentOverviewResponse {
    return true;
}

export function AgentOverviewResponseFromJSON(json: any): AgentOverviewResponse {
    return AgentOverviewResponseFromJSONTyped(json, false);
}

export function AgentOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'name': json['name'] == null ? undefined : json['name'],
        'port': json['port'] == null ? undefined : json['port'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(AgentTaskOverviewResponseFromJSON)),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function AgentOverviewResponseToJSON(json: any): AgentOverviewResponse {
    return AgentOverviewResponseToJSONTyped(json, false);
}

export function AgentOverviewResponseToJSONTyped(value?: AgentOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'name': value['name'],
        'port': value['port'],
        'protocol': value['protocol'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(AgentTaskOverviewResponseToJSON)),
        'version': value['version'],
    };
}

