/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgentProtocol {
    AgentProtocol_UNKNOWN = 0,
    AgentProtocol_GRPC = 1,
    AgentProtocol_HTTP = 2
}


export function instanceOfAgentProtocol(value: any): boolean {
    for (const key in AgentProtocol) {
        if (Object.prototype.hasOwnProperty.call(AgentProtocol, key)) {
            if (AgentProtocol[key as keyof typeof AgentProtocol] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentProtocolFromJSON(json: any): AgentProtocol {
    return AgentProtocolFromJSONTyped(json, false);
}

export function AgentProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentProtocol {
    return json as AgentProtocol;
}

export function AgentProtocolToJSON(value?: AgentProtocol | null): any {
    return value as any;
}

export function AgentProtocolToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentProtocol {
    return value as AgentProtocol;
}

