/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentTaskResponse
 */
export interface AgentTaskResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentTaskResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentTaskResponse
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof AgentTaskResponse
     */
    inputParameters?: object;
    /**
     * 
     * @type {string}
     * @memberof AgentTaskResponse
     */
    name?: string;
    /**
     * 
     * @type {object}
     * @memberof AgentTaskResponse
     */
    outputParameters?: object;
}

/**
 * Check if a given object implements the AgentTaskResponse interface.
 */
export function instanceOfAgentTaskResponse(value: object): value is AgentTaskResponse {
    return true;
}

export function AgentTaskResponseFromJSON(json: any): AgentTaskResponse {
    return AgentTaskResponseFromJSONTyped(json, false);
}

export function AgentTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'inputParameters': json['inputParameters'] == null ? undefined : json['inputParameters'],
        'name': json['name'] == null ? undefined : json['name'],
        'outputParameters': json['outputParameters'] == null ? undefined : json['outputParameters'],
    };
}

export function AgentTaskResponseToJSON(json: any): AgentTaskResponse {
    return AgentTaskResponseToJSONTyped(json, false);
}

export function AgentTaskResponseToJSONTyped(value?: AgentTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'inputParameters': value['inputParameters'],
        'name': value['name'],
        'outputParameters': value['outputParameters'],
    };
}

