/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComparisonOperator } from './ComparisonOperator';
import {
    ComparisonOperatorFromJSON,
    ComparisonOperatorFromJSONTyped,
    ComparisonOperatorToJSON,
    ComparisonOperatorToJSONTyped,
} from './ComparisonOperator';

/**
 * 
 * @export
 * @interface CompareExpression
 */
export interface CompareExpression {
    /**
     * 
     * @type {string}
     * @memberof CompareExpression
     */
    field?: string;
    /**
     * 
     * @type {ComparisonOperator}
     * @memberof CompareExpression
     */
    operator?: ComparisonOperator;
    /**
     * 
     * @type {object}
     * @memberof CompareExpression
     */
    value?: object;
}



/**
 * Check if a given object implements the CompareExpression interface.
 */
export function instanceOfCompareExpression(value: object): value is CompareExpression {
    return true;
}

export function CompareExpressionFromJSON(json: any): CompareExpression {
    return CompareExpressionFromJSONTyped(json, false);
}

export function CompareExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompareExpression {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'operator': json['operator'] == null ? undefined : ComparisonOperatorFromJSON(json['operator']),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CompareExpressionToJSON(json: any): CompareExpression {
    return CompareExpressionToJSONTyped(json, false);
}

export function CompareExpressionToJSONTyped(value?: CompareExpression | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'operator': ComparisonOperatorToJSON(value['operator']),
        'value': value['value'],
    };
}

