/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ComparisonOperator {
    OperatorEquals = '=',
    OperatorNotEquals = '!=',
    OperatorGreaterThan = '>',
    OperatorLessThan = '<',
    OperatorGreaterEqual = '>=',
    OperatorLessEqual = '<=',
    OperatorIn = 'in'
}


export function instanceOfComparisonOperator(value: any): boolean {
    for (const key in ComparisonOperator) {
        if (Object.prototype.hasOwnProperty.call(ComparisonOperator, key)) {
            if (ComparisonOperator[key as keyof typeof ComparisonOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ComparisonOperatorFromJSON(json: any): ComparisonOperator {
    return ComparisonOperatorFromJSONTyped(json, false);
}

export function ComparisonOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonOperator {
    return json as ComparisonOperator;
}

export function ComparisonOperatorToJSON(value?: ComparisonOperator | null): any {
    return value as any;
}

export function ComparisonOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): ComparisonOperator {
    return value as ComparisonOperator;
}

