/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionCase
 */
export interface DecisionCase {
    /**
     * 
     * @type {string}
     * @memberof DecisionCase
     */
    condition: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionCase
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionCase
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DecisionCase
     */
    nextStepId: string;
}

/**
 * Check if a given object implements the DecisionCase interface.
 */
export function instanceOfDecisionCase(value: object): value is DecisionCase {
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('nextStepId' in value) || value['nextStepId'] === undefined) return false;
    return true;
}

export function DecisionCaseFromJSON(json: any): DecisionCase {
    return DecisionCaseFromJSONTyped(json, false);
}

export function DecisionCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionCase {
    if (json == null) {
        return json;
    }
    return {
        
        'condition': json['condition'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'nextStepId': json['nextStepId'],
    };
}

export function DecisionCaseToJSON(json: any): DecisionCase {
    return DecisionCaseToJSONTyped(json, false);
}

export function DecisionCaseToJSONTyped(value?: DecisionCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition': value['condition'],
        'description': value['description'],
        'name': value['name'],
        'nextStepId': value['nextStepId'],
    };
}

