/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecisionCase } from './DecisionCase';
import {
    DecisionCaseFromJSON,
    DecisionCaseFromJSONTyped,
    DecisionCaseToJSON,
    DecisionCaseToJSONTyped,
} from './DecisionCase';

/**
 * 
 * @export
 * @interface DecisionConfig
 */
export interface DecisionConfig {
    /**
     * 
     * @type {Array<DecisionCase>}
     * @memberof DecisionConfig
     */
    cases?: Array<DecisionCase>;
}

/**
 * Check if a given object implements the DecisionConfig interface.
 */
export function instanceOfDecisionConfig(value: object): value is DecisionConfig {
    return true;
}

export function DecisionConfigFromJSON(json: any): DecisionConfig {
    return DecisionConfigFromJSONTyped(json, false);
}

export function DecisionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'cases': json['cases'] == null ? undefined : ((json['cases'] as Array<any>).map(DecisionCaseFromJSON)),
    };
}

export function DecisionConfigToJSON(json: any): DecisionConfig {
    return DecisionConfigToJSONTyped(json, false);
}

export function DecisionConfigToJSONTyped(value?: DecisionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cases': value['cases'] == null ? undefined : ((value['cases'] as Array<any>).map(DecisionCaseToJSON)),
    };
}

