/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompareExpression } from './CompareExpression';
import {
    CompareExpressionFromJSON,
    CompareExpressionFromJSONTyped,
    CompareExpressionToJSON,
    CompareExpressionToJSONTyped,
} from './CompareExpression';

/**
 * 
 * @export
 * @interface Expression
 */
export interface Expression {
    /**
     * 
     * @type {Array<Expression>}
     * @memberof Expression
     */
    and?: Array<Expression>;
    /**
     * 
     * @type {CompareExpression}
     * @memberof Expression
     */
    compare?: CompareExpression;
    /**
     * 
     * @type {Expression}
     * @memberof Expression
     */
    not?: Expression;
    /**
     * 
     * @type {Array<Expression>}
     * @memberof Expression
     */
    or?: Array<Expression>;
}

/**
 * Check if a given object implements the Expression interface.
 */
export function instanceOfExpression(value: object): value is Expression {
    return true;
}

export function ExpressionFromJSON(json: any): Expression {
    return ExpressionFromJSONTyped(json, false);
}

export function ExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Expression {
    if (json == null) {
        return json;
    }
    return {
        
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(ExpressionFromJSON)),
        'compare': json['compare'] == null ? undefined : CompareExpressionFromJSON(json['compare']),
        'not': json['not'] == null ? undefined : ExpressionFromJSON(json['not']),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(ExpressionFromJSON)),
    };
}

export function ExpressionToJSON(json: any): Expression {
    return ExpressionToJSONTyped(json, false);
}

export function ExpressionToJSONTyped(value?: Expression | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(ExpressionToJSON)),
        'compare': CompareExpressionToJSON(value['compare']),
        'not': ExpressionToJSON(value['not']),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(ExpressionToJSON)),
    };
}

