/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForkBranch
 */
export interface ForkBranch {
    /**
     * 
     * @type {string}
     * @memberof ForkBranch
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ForkBranch
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ForkBranch
     */
    nextStepId: string;
}

/**
 * Check if a given object implements the ForkBranch interface.
 */
export function instanceOfForkBranch(value: object): value is ForkBranch {
    if (!('nextStepId' in value) || value['nextStepId'] === undefined) return false;
    return true;
}

export function ForkBranchFromJSON(json: any): ForkBranch {
    return ForkBranchFromJSONTyped(json, false);
}

export function ForkBranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkBranch {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'nextStepId': json['nextStepId'],
    };
}

export function ForkBranchToJSON(json: any): ForkBranch {
    return ForkBranchToJSONTyped(json, false);
}

export function ForkBranchToJSONTyped(value?: ForkBranch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'nextStepId': value['nextStepId'],
    };
}

