/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForkBranch } from './ForkBranch';
import {
    ForkBranchFromJSON,
    ForkBranchFromJSONTyped,
    ForkBranchToJSON,
    ForkBranchToJSONTyped,
} from './ForkBranch';

/**
 * 
 * @export
 * @interface ForkConfig
 */
export interface ForkConfig {
    /**
     * 
     * @type {Array<ForkBranch>}
     * @memberof ForkConfig
     */
    branches: Array<ForkBranch>;
    /**
     * 
     * @type {string}
     * @memberof ForkConfig
     */
    joinStepId: string;
}

/**
 * Check if a given object implements the ForkConfig interface.
 */
export function instanceOfForkConfig(value: object): value is ForkConfig {
    if (!('branches' in value) || value['branches'] === undefined) return false;
    if (!('joinStepId' in value) || value['joinStepId'] === undefined) return false;
    return true;
}

export function ForkConfigFromJSON(json: any): ForkConfig {
    return ForkConfigFromJSONTyped(json, false);
}

export function ForkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'branches': ((json['branches'] as Array<any>).map(ForkBranchFromJSON)),
        'joinStepId': json['joinStepId'],
    };
}

export function ForkConfigToJSON(json: any): ForkConfig {
    return ForkConfigToJSONTyped(json, false);
}

export function ForkConfigToJSONTyped(value?: ForkConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branches': ((value['branches'] as Array<any>).map(ForkBranchToJSON)),
        'joinStepId': value['joinStepId'],
    };
}

