/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinConfig
 */
export interface JoinConfig {
    /**
     * 
     * @type {Array<string>}
     * @memberof JoinConfig
     */
    incomingStepIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof JoinConfig
     */
    nextStepId?: string;
}

/**
 * Check if a given object implements the JoinConfig interface.
 */
export function instanceOfJoinConfig(value: object): value is JoinConfig {
    if (!('incomingStepIds' in value) || value['incomingStepIds'] === undefined) return false;
    return true;
}

export function JoinConfigFromJSON(json: any): JoinConfig {
    return JoinConfigFromJSONTyped(json, false);
}

export function JoinConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'incomingStepIds': json['incomingStepIds'],
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
    };
}

export function JoinConfigToJSON(json: any): JoinConfig {
    return JoinConfigToJSONTyped(json, false);
}

export function JoinConfigToJSONTyped(value?: JoinConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incomingStepIds': value['incomingStepIds'],
        'nextStepId': value['nextStepId'],
    };
}

