/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum StepType {
    StepTypeTask = 'task',
    StepTypeWorkflow = 'workflow',
    StepTypeWait = 'wait',
    StepTypeDecision = 'decision',
    StepTypeFork = 'fork',
    StepTypeJoin = 'join'
}


export function instanceOfStepType(value: any): boolean {
    for (const key in StepType) {
        if (Object.prototype.hasOwnProperty.call(StepType, key)) {
            if (StepType[key as keyof typeof StepType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StepTypeFromJSON(json: any): StepType {
    return StepTypeFromJSONTyped(json, false);
}

export function StepTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepType {
    return json as StepType;
}

export function StepTypeToJSON(value?: StepType | null): any {
    return value as any;
}

export function StepTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StepType {
    return value as StepType;
}

