/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepParameterType } from './StepParameterType';
import {
    StepParameterTypeFromJSON,
    StepParameterTypeFromJSONTyped,
    StepParameterTypeToJSON,
    StepParameterTypeToJSONTyped,
} from './StepParameterType';

/**
 * 
 * @export
 * @interface StepDefinitionParameter
 */
export interface StepDefinitionParameter {
    /**
     * 
     * @type {StepParameterType}
     * @memberof StepDefinitionParameter
     */
    type: StepParameterType;
    /**
     * 
     * @type {object}
     * @memberof StepDefinitionParameter
     */
    value: object;
}



/**
 * Check if a given object implements the StepDefinitionParameter interface.
 */
export function instanceOfStepDefinitionParameter(value: object): value is StepDefinitionParameter {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function StepDefinitionParameterFromJSON(json: any): StepDefinitionParameter {
    return StepDefinitionParameterFromJSONTyped(json, false);
}

export function StepDefinitionParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepDefinitionParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'type': StepParameterTypeFromJSON(json['type']),
        'value': json['value'],
    };
}

export function StepDefinitionParameterToJSON(json: any): StepDefinitionParameter {
    return StepDefinitionParameterToJSONTyped(json, false);
}

export function StepDefinitionParameterToJSONTyped(value?: StepDefinitionParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': StepParameterTypeToJSON(value['type']),
        'value': value['value'],
    };
}

