/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum StepStatus {
    StepStatusPending = 'pending',
    StepStatusRunning = 'running',
    StepStatusCompleted = 'completed',
    StepStatusFailed = 'failed',
    StepStatusCancelled = 'cancelled'
}


export function instanceOfStepStatus(value: any): boolean {
    for (const key in StepStatus) {
        if (Object.prototype.hasOwnProperty.call(StepStatus, key)) {
            if (StepStatus[key as keyof typeof StepStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StepStatusFromJSON(json: any): StepStatus {
    return StepStatusFromJSONTyped(json, false);
}

export function StepStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepStatus {
    return json as StepStatus;
}

export function StepStatusToJSON(value?: StepStatus | null): any {
    return value as any;
}

export function StepStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): StepStatus {
    return value as StepStatus;
}

