/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepStatus } from './StepStatus';
import {
    StepStatusFromJSON,
    StepStatusFromJSONTyped,
    StepStatusToJSON,
    StepStatusToJSONTyped,
} from './StepStatus';

/**
 * 
 * @export
 * @interface StepInstance
 */
export interface StepInstance {
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    completedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StepInstance
     */
    input?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StepInstance
     */
    output?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof StepInstance
     */
    progress?: number;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    startedAt?: string;
    /**
     * 
     * @type {StepStatus}
     * @memberof StepInstance
     */
    status?: StepStatus;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    stepId?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    workflowDefinitionId?: string;
    /**
     * 
     * @type {string}
     * @memberof StepInstance
     */
    workflowInstanceId?: string;
}



/**
 * Check if a given object implements the StepInstance interface.
 */
export function instanceOfStepInstance(value: object): value is StepInstance {
    return true;
}

export function StepInstanceFromJSON(json: any): StepInstance {
    return StepInstanceFromJSONTyped(json, false);
}

export function StepInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'completedAt': json['completedAt'] == null ? undefined : json['completedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'id': json['id'] == null ? undefined : json['id'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'status': json['status'] == null ? undefined : StepStatusFromJSON(json['status']),
        'stepId': json['stepId'] == null ? undefined : json['stepId'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'workflowDefinitionId': json['workflowDefinitionId'] == null ? undefined : json['workflowDefinitionId'],
        'workflowInstanceId': json['workflowInstanceId'] == null ? undefined : json['workflowInstanceId'],
    };
}

export function StepInstanceToJSON(json: any): StepInstance {
    return StepInstanceToJSONTyped(json, false);
}

export function StepInstanceToJSONTyped(value?: StepInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completedAt': value['completedAt'],
        'createdAt': value['createdAt'],
        'errorMessage': value['errorMessage'],
        'id': value['id'],
        'input': value['input'],
        'output': value['output'],
        'progress': value['progress'],
        'startedAt': value['startedAt'],
        'status': StepStatusToJSON(value['status']),
        'stepId': value['stepId'],
        'updatedAt': value['updatedAt'],
        'workflowDefinitionId': value['workflowDefinitionId'],
        'workflowInstanceId': value['workflowInstanceId'],
    };
}

