/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum StepParameterType {
    StepParameterTypeConstant = 'constant',
    StepParameterTypeWorkflow = 'workflowInput',
    StepParameterTypeTaskOutput = 'taskOutput'
}


export function instanceOfStepParameterType(value: any): boolean {
    for (const key in StepParameterType) {
        if (Object.prototype.hasOwnProperty.call(StepParameterType, key)) {
            if (StepParameterType[key as keyof typeof StepParameterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StepParameterTypeFromJSON(json: any): StepParameterType {
    return StepParameterTypeFromJSONTyped(json, false);
}

export function StepParameterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepParameterType {
    return json as StepParameterType;
}

export function StepParameterTypeToJSON(value?: StepParameterType | null): any {
    return value as any;
}

export function StepParameterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StepParameterType {
    return value as StepParameterType;
}

