/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskConfig
 */
export interface TaskConfig {
    /**
     * 
     * @type {string}
     * @memberof TaskConfig
     */
    nextStepId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskConfig
     */
    taskDefinitionId?: string;
}

/**
 * Check if a given object implements the TaskConfig interface.
 */
export function instanceOfTaskConfig(value: object): value is TaskConfig {
    return true;
}

export function TaskConfigFromJSON(json: any): TaskConfig {
    return TaskConfigFromJSONTyped(json, false);
}

export function TaskConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
        'taskDefinitionId': json['taskDefinitionId'] == null ? undefined : json['taskDefinitionId'],
    };
}

export function TaskConfigToJSON(json: any): TaskConfig {
    return TaskConfigToJSONTyped(json, false);
}

export function TaskConfigToJSONTyped(value?: TaskConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextStepId': value['nextStepId'],
        'taskDefinitionId': value['taskDefinitionId'],
    };
}

