/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDefinitionResponse
 */
export interface TaskDefinitionResponse {
    /**
     * 
     * @type {string}
     * @memberof TaskDefinitionResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDefinitionResponse
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TaskDefinitionResponse
     */
    inputParameters?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof TaskDefinitionResponse
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TaskDefinitionResponse
     */
    outputParameters?: { [key: string]: any; };
}

/**
 * Check if a given object implements the TaskDefinitionResponse interface.
 */
export function instanceOfTaskDefinitionResponse(value: object): value is TaskDefinitionResponse {
    return true;
}

export function TaskDefinitionResponseFromJSON(json: any): TaskDefinitionResponse {
    return TaskDefinitionResponseFromJSONTyped(json, false);
}

export function TaskDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDefinitionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'inputParameters': json['inputParameters'] == null ? undefined : json['inputParameters'],
        'name': json['name'] == null ? undefined : json['name'],
        'outputParameters': json['outputParameters'] == null ? undefined : json['outputParameters'],
    };
}

export function TaskDefinitionResponseToJSON(json: any): TaskDefinitionResponse {
    return TaskDefinitionResponseToJSONTyped(json, false);
}

export function TaskDefinitionResponseToJSONTyped(value?: TaskDefinitionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'inputParameters': value['inputParameters'],
        'name': value['name'],
        'outputParameters': value['outputParameters'],
    };
}

