/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStepDefinition } from './WorkflowStepDefinition';
import {
    WorkflowStepDefinitionFromJSON,
    WorkflowStepDefinitionFromJSONTyped,
    WorkflowStepDefinitionToJSON,
    WorkflowStepDefinitionToJSONTyped,
} from './WorkflowStepDefinition';

/**
 * 
 * @export
 * @interface UpdateWorkflowDefRequest
 */
export interface UpdateWorkflowDefRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkflowDefRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkflowDefRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<WorkflowStepDefinition>}
     * @memberof UpdateWorkflowDefRequest
     */
    steps?: Array<WorkflowStepDefinition>;
}

/**
 * Check if a given object implements the UpdateWorkflowDefRequest interface.
 */
export function instanceOfUpdateWorkflowDefRequest(value: object): value is UpdateWorkflowDefRequest {
    return true;
}

export function UpdateWorkflowDefRequestFromJSON(json: any): UpdateWorkflowDefRequest {
    return UpdateWorkflowDefRequestFromJSONTyped(json, false);
}

export function UpdateWorkflowDefRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkflowDefRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(WorkflowStepDefinitionFromJSON)),
    };
}

export function UpdateWorkflowDefRequestToJSON(json: any): UpdateWorkflowDefRequest {
    return UpdateWorkflowDefRequestToJSONTyped(json, false);
}

export function UpdateWorkflowDefRequestToJSONTyped(value?: UpdateWorkflowDefRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(WorkflowStepDefinitionToJSON)),
    };
}

