/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepDefinitionParameter } from './StepDefinitionParameter';
import {
    StepDefinitionParameterFromJSON,
    StepDefinitionParameterFromJSONTyped,
    StepDefinitionParameterToJSON,
    StepDefinitionParameterToJSONTyped,
} from './StepDefinitionParameter';

/**
 * 
 * @export
 * @interface WaitConfig
 */
export interface WaitConfig {
    /**
     * 
     * @type {StepDefinitionParameter}
     * @memberof WaitConfig
     */
    durationSeconds?: StepDefinitionParameter;
    /**
     * 
     * @type {string}
     * @memberof WaitConfig
     */
    nextStepId?: string;
}

/**
 * Check if a given object implements the WaitConfig interface.
 */
export function instanceOfWaitConfig(value: object): value is WaitConfig {
    return true;
}

export function WaitConfigFromJSON(json: any): WaitConfig {
    return WaitConfigFromJSONTyped(json, false);
}

export function WaitConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'durationSeconds': json['durationSeconds'] == null ? undefined : StepDefinitionParameterFromJSON(json['durationSeconds']),
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
    };
}

export function WaitConfigToJSON(json: any): WaitConfig {
    return WaitConfigToJSONTyped(json, false);
}

export function WaitConfigToJSONTyped(value?: WaitConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'durationSeconds': StepDefinitionParameterToJSON(value['durationSeconds']),
        'nextStepId': value['nextStepId'],
    };
}

