/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowConfig
 */
export interface WorkflowConfig {
    /**
     * 
     * @type {string}
     * @memberof WorkflowConfig
     */
    nextStepId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowConfig
     */
    workflowDefinitionId?: string;
}

/**
 * Check if a given object implements the WorkflowConfig interface.
 */
export function instanceOfWorkflowConfig(value: object): value is WorkflowConfig {
    return true;
}

export function WorkflowConfigFromJSON(json: any): WorkflowConfig {
    return WorkflowConfigFromJSONTyped(json, false);
}

export function WorkflowConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
        'workflowDefinitionId': json['workflowDefinitionId'] == null ? undefined : json['workflowDefinitionId'],
    };
}

export function WorkflowConfigToJSON(json: any): WorkflowConfig {
    return WorkflowConfigToJSONTyped(json, false);
}

export function WorkflowConfigToJSONTyped(value?: WorkflowConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextStepId': value['nextStepId'],
        'workflowDefinitionId': value['workflowDefinitionId'],
    };
}

