/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepDefinitionParameter } from './StepDefinitionParameter';
import {
    StepDefinitionParameterFromJSON,
    StepDefinitionParameterFromJSONTyped,
    StepDefinitionParameterToJSON,
    StepDefinitionParameterToJSONTyped,
} from './StepDefinitionParameter';
import type { DecisionConfig } from './DecisionConfig';
import {
    DecisionConfigFromJSON,
    DecisionConfigFromJSONTyped,
    DecisionConfigToJSON,
    DecisionConfigToJSONTyped,
} from './DecisionConfig';
import type { WaitConfig } from './WaitConfig';
import {
    WaitConfigFromJSON,
    WaitConfigFromJSONTyped,
    WaitConfigToJSON,
    WaitConfigToJSONTyped,
} from './WaitConfig';
import type { WorkflowConfig } from './WorkflowConfig';
import {
    WorkflowConfigFromJSON,
    WorkflowConfigFromJSONTyped,
    WorkflowConfigToJSON,
    WorkflowConfigToJSONTyped,
} from './WorkflowConfig';
import type { ForkConfig } from './ForkConfig';
import {
    ForkConfigFromJSON,
    ForkConfigFromJSONTyped,
    ForkConfigToJSON,
    ForkConfigToJSONTyped,
} from './ForkConfig';
import type { StepType } from './StepType';
import {
    StepTypeFromJSON,
    StepTypeFromJSONTyped,
    StepTypeToJSON,
    StepTypeToJSONTyped,
} from './StepType';
import type { JoinConfig } from './JoinConfig';
import {
    JoinConfigFromJSON,
    JoinConfigFromJSONTyped,
    JoinConfigToJSON,
    JoinConfigToJSONTyped,
} from './JoinConfig';
import type { TaskConfig } from './TaskConfig';
import {
    TaskConfigFromJSON,
    TaskConfigFromJSONTyped,
    TaskConfigToJSON,
    TaskConfigToJSONTyped,
} from './TaskConfig';

/**
 * 
 * @export
 * @interface WorkflowStepDefinition
 */
export interface WorkflowStepDefinition {
    /**
     * 
     * @type {DecisionConfig}
     * @memberof WorkflowStepDefinition
     */
    decisionConfig?: DecisionConfig;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStepDefinition
     */
    description?: string;
    /**
     * 
     * @type {ForkConfig}
     * @memberof WorkflowStepDefinition
     */
    forkConfig?: ForkConfig;
    /**
     * 
     * @type {JoinConfig}
     * @memberof WorkflowStepDefinition
     */
    joinConfig?: JoinConfig;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStepDefinition
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStepDefinition
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: StepDefinitionParameter; }}
     * @memberof WorkflowStepDefinition
     */
    parameters?: { [key: string]: StepDefinitionParameter; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStepDefinition
     */
    stepDefinitionId: string;
    /**
     * 
     * @type {TaskConfig}
     * @memberof WorkflowStepDefinition
     */
    taskConfig?: TaskConfig;
    /**
     * 
     * @type {StepType}
     * @memberof WorkflowStepDefinition
     */
    type: StepType;
    /**
     * 
     * @type {WaitConfig}
     * @memberof WorkflowStepDefinition
     */
    waitConfig?: WaitConfig;
    /**
     * 
     * @type {WorkflowConfig}
     * @memberof WorkflowStepDefinition
     */
    workflowConfig?: WorkflowConfig;
}



/**
 * Check if a given object implements the WorkflowStepDefinition interface.
 */
export function instanceOfWorkflowStepDefinition(value: object): value is WorkflowStepDefinition {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('stepDefinitionId' in value) || value['stepDefinitionId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WorkflowStepDefinitionFromJSON(json: any): WorkflowStepDefinition {
    return WorkflowStepDefinitionFromJSONTyped(json, false);
}

export function WorkflowStepDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'decisionConfig': json['decisionConfig'] == null ? undefined : DecisionConfigFromJSON(json['decisionConfig']),
        'description': json['description'] == null ? undefined : json['description'],
        'forkConfig': json['forkConfig'] == null ? undefined : ForkConfigFromJSON(json['forkConfig']),
        'joinConfig': json['joinConfig'] == null ? undefined : JoinConfigFromJSON(json['joinConfig']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'parameters': json['parameters'] == null ? undefined : (mapValues(json['parameters'], StepDefinitionParameterFromJSON)),
        'stepDefinitionId': json['stepDefinitionId'],
        'taskConfig': json['taskConfig'] == null ? undefined : TaskConfigFromJSON(json['taskConfig']),
        'type': StepTypeFromJSON(json['type']),
        'waitConfig': json['waitConfig'] == null ? undefined : WaitConfigFromJSON(json['waitConfig']),
        'workflowConfig': json['workflowConfig'] == null ? undefined : WorkflowConfigFromJSON(json['workflowConfig']),
    };
}

export function WorkflowStepDefinitionToJSON(json: any): WorkflowStepDefinition {
    return WorkflowStepDefinitionToJSONTyped(json, false);
}

export function WorkflowStepDefinitionToJSONTyped(value?: WorkflowStepDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decisionConfig': DecisionConfigToJSON(value['decisionConfig']),
        'description': value['description'],
        'forkConfig': ForkConfigToJSON(value['forkConfig']),
        'joinConfig': JoinConfigToJSON(value['joinConfig']),
        'metadata': value['metadata'],
        'name': value['name'],
        'parameters': value['parameters'] == null ? undefined : (mapValues(value['parameters'], StepDefinitionParameterToJSON)),
        'stepDefinitionId': value['stepDefinitionId'],
        'taskConfig': TaskConfigToJSON(value['taskConfig']),
        'type': StepTypeToJSON(value['type']),
        'waitConfig': WaitConfigToJSON(value['waitConfig']),
        'workflowConfig': WorkflowConfigToJSON(value['workflowConfig']),
    };
}

