/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowParameterDefinition } from './WorkflowParameterDefinition';
import {
    WorkflowParameterDefinitionFromJSON,
    WorkflowParameterDefinitionFromJSONTyped,
    WorkflowParameterDefinitionToJSON,
    WorkflowParameterDefinitionToJSONTyped,
} from './WorkflowParameterDefinition';
import type { WorkflowStepDefinition } from './WorkflowStepDefinition';
import {
    WorkflowStepDefinitionFromJSON,
    WorkflowStepDefinitionFromJSONTyped,
    WorkflowStepDefinitionToJSON,
    WorkflowStepDefinitionToJSONTyped,
} from './WorkflowStepDefinition';

/**
 * 
 * @export
 * @interface WorkflowDefinition
 */
export interface WorkflowDefinition {
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    id: string;
    /**
     * 
     * @type {Array<WorkflowParameterDefinition>}
     * @memberof WorkflowDefinition
     */
    inputParameters?: Array<WorkflowParameterDefinition>;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowDefinition
     */
    isEnabled: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowDefinition
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof WorkflowDefinition
     */
    outputParameters?: object;
    /**
     * 
     * @type {Array<WorkflowStepDefinition>}
     * @memberof WorkflowDefinition
     */
    steps: Array<WorkflowStepDefinition>;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDefinition
     */
    version: string;
}

/**
 * Check if a given object implements the WorkflowDefinition interface.
 */
export function instanceOfWorkflowDefinition(value: object): value is WorkflowDefinition {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function WorkflowDefinitionFromJSON(json: any): WorkflowDefinition {
    return WorkflowDefinitionFromJSONTyped(json, false);
}

export function WorkflowDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'inputParameters': json['inputParameters'] == null ? undefined : ((json['inputParameters'] as Array<any>).map(WorkflowParameterDefinitionFromJSON)),
        'isEnabled': json['isEnabled'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'outputParameters': json['outputParameters'] == null ? undefined : json['outputParameters'],
        'steps': ((json['steps'] as Array<any>).map(WorkflowStepDefinitionFromJSON)),
        'updatedAt': json['updatedAt'],
        'version': json['version'],
    };
}

export function WorkflowDefinitionToJSON(json: any): WorkflowDefinition {
    return WorkflowDefinitionToJSONTyped(json, false);
}

export function WorkflowDefinitionToJSONTyped(value?: WorkflowDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'inputParameters': value['inputParameters'] == null ? undefined : ((value['inputParameters'] as Array<any>).map(WorkflowParameterDefinitionToJSON)),
        'isEnabled': value['isEnabled'],
        'metadata': value['metadata'],
        'name': value['name'],
        'outputParameters': value['outputParameters'],
        'steps': ((value['steps'] as Array<any>).map(WorkflowStepDefinitionToJSON)),
        'updatedAt': value['updatedAt'],
        'version': value['version'],
    };
}

