/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum WorkflowStatus {
    WorkflowStatusPending = 'PENDING',
    WorkflowStatusRunning = 'RUNNING',
    WorkflowStatusCompleted = 'COMPLETED',
    WorkflowStatusFailed = 'FAILED',
    WorkflowStatusCancelled = 'CANCELLED'
}


export function instanceOfWorkflowStatus(value: any): boolean {
    for (const key in WorkflowStatus) {
        if (Object.prototype.hasOwnProperty.call(WorkflowStatus, key)) {
            if (WorkflowStatus[key as keyof typeof WorkflowStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkflowStatusFromJSON(json: any): WorkflowStatus {
    return WorkflowStatusFromJSONTyped(json, false);
}

export function WorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStatus {
    return json as WorkflowStatus;
}

export function WorkflowStatusToJSON(value?: WorkflowStatus | null): any {
    return value as any;
}

export function WorkflowStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowStatus {
    return value as WorkflowStatus;
}

