/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStatus } from './WorkflowStatus';
import {
    WorkflowStatusFromJSON,
    WorkflowStatusFromJSONTyped,
    WorkflowStatusToJSON,
    WorkflowStatusToJSONTyped,
} from './WorkflowStatus';

/**
 * 
 * @export
 * @interface WorkflowInstance
 */
export interface WorkflowInstance {
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    completedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowInstance
     */
    input?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowInstance
     */
    output?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    startedAt?: string;
    /**
     * 
     * @type {WorkflowStatus}
     * @memberof WorkflowInstance
     */
    status?: WorkflowStatus;
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowInstance
     */
    workflowDefinitionId?: string;
}



/**
 * Check if a given object implements the WorkflowInstance interface.
 */
export function instanceOfWorkflowInstance(value: object): value is WorkflowInstance {
    return true;
}

export function WorkflowInstanceFromJSON(json: any): WorkflowInstance {
    return WorkflowInstanceFromJSONTyped(json, false);
}

export function WorkflowInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'completedAt': json['completedAt'] == null ? undefined : json['completedAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'id': json['id'] == null ? undefined : json['id'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'status': json['status'] == null ? undefined : WorkflowStatusFromJSON(json['status']),
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'workflowDefinitionId': json['workflowDefinitionId'] == null ? undefined : json['workflowDefinitionId'],
    };
}

export function WorkflowInstanceToJSON(json: any): WorkflowInstance {
    return WorkflowInstanceToJSONTyped(json, false);
}

export function WorkflowInstanceToJSONTyped(value?: WorkflowInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completedAt': value['completedAt'],
        'createdAt': value['createdAt'],
        'errorMessage': value['errorMessage'],
        'id': value['id'],
        'input': value['input'],
        'output': value['output'],
        'startedAt': value['startedAt'],
        'status': WorkflowStatusToJSON(value['status']),
        'updatedAt': value['updatedAt'],
        'workflowDefinitionId': value['workflowDefinitionId'],
    };
}

