/* tslint:disable */
/* eslint-disable */
/**
 * Workflow Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowParameterDefinition
 */
export interface WorkflowParameterDefinition {
    /**
     * 
     * @type {object}
     * @memberof WorkflowParameterDefinition
     */
    _default?: object;
    /**
     * 
     * @type {string}
     * @memberof WorkflowParameterDefinition
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowParameterDefinition
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowParameterDefinition
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowParameterDefinition
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkflowParameterDefinition
     */
    type?: string;
}

/**
 * Check if a given object implements the WorkflowParameterDefinition interface.
 */
export function instanceOfWorkflowParameterDefinition(value: object): value is WorkflowParameterDefinition {
    return true;
}

export function WorkflowParameterDefinitionFromJSON(json: any): WorkflowParameterDefinition {
    return WorkflowParameterDefinitionFromJSONTyped(json, false);
}

export function WorkflowParameterDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowParameterDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        '_default': json['default'] == null ? undefined : json['default'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'required': json['required'] == null ? undefined : json['required'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WorkflowParameterDefinitionToJSON(json: any): WorkflowParameterDefinition {
    return WorkflowParameterDefinitionToJSONTyped(json, false);
}

export function WorkflowParameterDefinitionToJSONTyped(value?: WorkflowParameterDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default': value['_default'],
        'description': value['description'],
        'metadata': value['metadata'],
        'name': value['name'],
        'required': value['required'],
        'type': value['type'],
    };
}

